'use client';
import { Fragment, useEffect, useMemo, useState } from 'react';
import { api } from '@/lib/api';
import { Badge } from './common';
import { Detail, Drawer, Filters, Metric, PageHeader, TableShell } from './ui';
const labels:any={PRESENT:'حاضر',LATE:'متأخر',ABSENT:'غائب',LEAVE:'إجازة',PERMISSION:'إذن',WEEKEND:'راحة',HOLIDAY:'عطلة',NOT_STARTED:'لم يسجل',INCOMPLETE:'غير مكتمل',AUTO_CLOSED:'انصراف تلقائي',NOT_EMPLOYED:'خارج الخدمة'};
const short:any={PRESENT:'ح',LATE:'م',ABSENT:'غ',LEAVE:'ج',PERMISSION:'إ',WEEKEND:'ر',HOLIDAY:'ع',NOT_STARTED:'—',INCOMPLETE:'ن',AUTO_CLOSED:'ت',NOT_EMPLOYED:'خ'};
export default function AttendanceCalendar(){const [month,setMonth]=useState(new Date().toISOString().slice(0,7));const[report,setReport]=useState<any>(null);const[q,setQ]=useState('');const[status,setStatus]=useState('ALL');const[busy,setBusy]=useState(false);const[selected,setSelected]=useState<any>(null);
 async function load(){setBusy(true);try{setReport(await api<any>('attendance_monthly_report',{month}))}catch(e:any){window.dispatchEvent(new CustomEvent('hr:toast',{detail:{message:e.message||'تعذر تحميل تقويم الحضور',type:'error'}}))}finally{setBusy(false)}} useEffect(()=>{void load()},[month]);
 const employees=useMemo(()=>{const map=new Map<string,any>();for(const r of Array.isArray(report?.rows)?report.rows:[]){if(!map.has(r.employee_id))map.set(r.employee_id,{employee_id:r.employee_id,name:r.employee_name,days:{}});map.get(r.employee_id).days[r.date]=r}return Array.from(map.values()).filter((e:any)=>!q||String(e.name).includes(q))},[report,q]);
 const days=useMemo(()=>{const out:string[]=[];const d=new Date(`${month}-01T00:00:00Z`);while(d.getUTCMonth()===Number(month.slice(5))-1){out.push(d.toISOString().slice(0,10));d.setUTCDate(d.getUTCDate()+1)}return out},[month]);
 const visible=employees.filter((e:any)=>status==='ALL'||Object.values(e.days).some((x:any)=>x.status===status));
 return <section className="panel page-panel"><PageHeader title="تقويم الحضور" subtitle="رؤية يومية موحدة للحضور والإجازات والأذونات والراحة والعطلات." eyebrow="إدارة الحضور" actions={<button className="secondary" onClick={load} disabled={busy}>تحديث التقويم</button>}/>
 <div className="ux-filters"><div className="ux-filters-fields"><label className="ux-field"><span>الشهر</span><input type="month" value={month} onChange={e=>setMonth(e.target.value)}/></label><label className="ux-field"><span>بحث عن موظف</span><input value={q} onChange={e=>setQ(e.target.value)} placeholder="اسم الموظف"/></label><label className="ux-field"><span>الحالة</span><select value={status} onChange={e=>setStatus(e.target.value)}><option value="ALL">كل الحالات</option>{Object.entries(labels).map(([k,v])=><option key={k} value={k}>{v as string}</option>)}</select></label></div></div>
 <div className="ux-metric-grid"><Metric label="الموظفون" value={visible.length} icon="users"/><Metric label="أيام الحضور" value={(report?.summary?.PRESENT??0)} tone="green" icon="check"/><Metric label="التأخير" value={(report?.summary?.LATE??0)} tone="amber" icon="attendance"/><Metric label="الغياب" value={(report?.summary?.ABSENT??0)} tone="red" icon="alert"/></div>
 {busy?<div className="empty-note">جاري تحميل التقويم…</div>:<><div className="attendance-calendar-wrap"><table className="attendance-calendar"><thead><tr><th className="employee-col">الموظف</th>{days.map(d=><th key={d}>{Number(d.slice(8,10))}</th>)}</tr></thead><tbody>{visible.map((e:any)=><Fragment key={e.employee_id}><tr><th className="employee-col" onClick={()=>setSelected(e)} style={{cursor:'pointer'}}><strong>{e.name}</strong><small>{e.employee_id}</small></th>{days.map(d=>{const r=e.days[d]||{status:'NOT_STARTED'};return <td key={d} title={`${labels[r.status]||r.status}${r.check_in?` • حضور ${r.check_in}`:''}${r.check_out?` • انصراف ${r.check_out}`:''}`} className={`calendar-cell status-${String(r.status).toLowerCase()}`} onClick={()=>setSelected({...e,...r,date:d})}>{short[r.status]||'؟'}</td>})}</tr></Fragment>)}</tbody></table></div><div className="attendance-calendar-legend">{Object.entries(labels).map(([k,v])=><span key={k} className={`calendar-legend-item status-${k.toLowerCase()}`}><i/>{v as string}</span>)}</div></>}
 <Drawer open={!!selected} title={selected?.name||'تفاصيل اليوم'} subtitle={selected?.date||selected?.employee_id} onClose={()=>setSelected(null)}><div className="ux-detail-grid"><Detail label="التاريخ" value={selected?.date}/><Detail label="الحالة"><Badge status={selected?.status}/></Detail><Detail label="الحضور" value={selected?.check_in}/><Detail label="الانصراف" value={selected?.check_out}/><Detail label="التأخير" value={selected?.late_minutes?`${selected.late_minutes} دقيقة`:'—'}/><Detail label="ساعات العمل" value={selected?.worked_minutes?`${Math.floor(Number(selected.worked_minutes)/60)} ساعة`:'—'}/></div></Drawer>
 </section>}
