
'use client';
import { Fragment, useEffect, useMemo, useState } from 'react';
import { api } from '@/lib/api';

const labels:any={PRESENT:'حاضر',LATE:'متأخر',ABSENT:'غائب',LEAVE:'إجازة',PERMISSION:'إذن',WEEKEND:'راحة',HOLIDAY:'عطلة',NOT_STARTED:'لم يسجل',INCOMPLETE:'ناقص',AUTO_CLOSED:'تلقائي',NOT_EMPLOYED:'خارج الخدمة'};
const short:any={PRESENT:'ح',LATE:'م',ABSENT:'غ',LEAVE:'ج',PERMISSION:'إ',WEEKEND:'ر',HOLIDAY:'ع',NOT_STARTED:'—',INCOMPLETE:'ن',AUTO_CLOSED:'ت',NOT_EMPLOYED:'خ'};
export default function AttendanceCalendar(){
 const [month,setMonth]=useState(new Date().toISOString().slice(0,7)); const [report,setReport]=useState<any>(null); const [q,setQ]=useState(''); const [status,setStatus]=useState('ALL'); const [busy,setBusy]=useState(false);
 async function load(){setBusy(true);try{setReport(await api<any>('attendance_monthly_report',{month}));}catch(e:any){window.dispatchEvent(new CustomEvent('hr:toast',{detail:{message:e.message||'تعذر تحميل تقويم الحضور',type:'error'}}));}finally{setBusy(false)}}
 useEffect(()=>{void load()},[month]);
 const employees=useMemo(()=>{const map=new Map<string,any>();for(const r of (Array.isArray(report?.rows)?report.rows:[])){if(!map.has(r.employee_id))map.set(r.employee_id,{employee_id:r.employee_id,name:r.employee_name,days:{}});map.get(r.employee_id).days[r.date]=r;} return Array.from(map.values()).filter((e:any)=>!q || String(e.name).includes(q));},[report,q]);
 const days=useMemo(()=>{const out:string[]=[];const d=new Date(`${month}-01T00:00:00Z`);while(d.getUTCMonth()===Number(month.slice(5))-1){out.push(d.toISOString().slice(0,10));d.setUTCDate(d.getUTCDate()+1)}return out},[month]);
 const visible=employees.filter((e:any)=>status==='ALL'||Object.values(e.days).some((x:any)=>x.status===status));
 return <section className="panel page-panel attendance-calendar-page"><div className="panel-head"><div><h2>تقويم الحضور</h2><p>حالة كل موظف في كل يوم وفق الوردية والإجازة والإذن والعطلات والراحة.</p></div><div className="attendance-calendar-tools"><label>الشهر<input type="month" value={month} onChange={e=>setMonth(e.target.value)}/></label><label>بحث<input value={q} onChange={e=>setQ(e.target.value)} placeholder="اسم الموظف"/></label><label>الحالة<select value={status} onChange={e=>setStatus(e.target.value)}><option value="ALL">كل الحالات</option>{Object.entries(labels).map(([k,v])=><option key={k} value={k}>{v as string}</option>)}</select></label></div></div>{busy&&<div className="empty-note">جاري تحميل التقويم…</div>}{!busy&&<><div className="attendance-calendar-legend">{Object.entries(labels).map(([k,v])=><span key={k} className={`calendar-legend-item status-${k.toLowerCase()}`}><i></i>{v as string}</span>)}</div><div className="attendance-calendar-wrap"><table className="attendance-calendar"><thead><tr><th className="employee-col">الموظف</th>{days.map(d=><th key={d} title={d}>{Number(d.slice(8,10))}</th>)}</tr></thead><tbody>{visible.map((e:any)=><Fragment key={e.employee_id}><tr><th className="employee-col"><strong>{e.name}</strong><small>{e.employee_id}</small></th>{days.map(d=>{const r=e.days[d]||{status:'NOT_STARTED',status_label:'لم يسجل'};const ok=status==='ALL'||r.status===status;return <td key={d} className={`calendar-cell status-${String(r.status).toLowerCase()} ${ok?'':'dim'}`} title={`${r.status_label||labels[r.status]||r.status}${r.check_in?` • حضور ${r.check_in}`:''}${r.check_out?` • انصراف ${r.check_out}`:''}`}>{short[r.status]||'؟'}</td>})}</tr></Fragment>)}</tbody></table></div></>}</section>
}
