'use client';
import { useEffect, useState } from 'react';
import Icon from './Icon';

export function Kpi({title,value,icon,danger}:{title:string;value:any;icon:string;danger?:boolean}){return <div className={`kpi ${danger?'danger-kpi':''}`}><div className="kpi-icon"><Icon name={icon} size={21}/></div><div><span>{title}</span><strong>{value}</strong></div><em>اليوم</em></div>}

export function Table({headers,rows}:{headers:string[];rows:any[][]}){const safeRows=Array.isArray(rows)?rows:[]; const safeHeaders=Array.isArray(headers)?headers:[]; const [mobile,setMobile]=useState(false);useEffect(()=>{const m=window.matchMedia('(max-width: 800px)');const sync=()=>setMobile(m.matches);sync();m.addEventListener('change',sync);return()=>m.removeEventListener('change',sync)},[]);if(mobile)return <div className="hr-mobile-records">{safeRows.map((r,i)=><article className="hr-mobile-record" key={i}><div className="hr-mobile-record-head"><strong>{String(r[0]??'—')}</strong><span>{String(r[safeHeaders.length-1]??'—')}</span></div>{r.slice(1,-1).map((v,j)=><div className="hr-mobile-field" key={j}><span>{safeHeaders[j+1]}</span><b>{typeof v === 'string' || typeof v === 'number' ? String(v??'—') : v}</b></div>)}</article>)}</div>;return <div className="table-wrap hr-responsive-table"><table><thead><tr>{safeHeaders.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{safeRows.map((r,i)=><tr key={i}>{r.map((v,j)=><td key={j}>{typeof v === 'string' || typeof v === 'number' ? String(v??'—') : v}</td>)}</tr>)}</tbody></table></div>}
export function Badge({status}:{status?:unknown}){const value=String(status??'').toUpperCase();const map:any={ACTIVE:['نشط','success'],INACTIVE:['غير نشط','muted'],APPROVED:['معتمد','success'],REJECTED:['مرفوض','danger'],PENDING_HR:['بانتظار الموارد البشرية','warning'],PENDING_MANAGER:['بانتظار المدير','warning'],PENDING:['بانتظار الاعتماد','warning'],SUBMITTED:['مرسل للاعتماد','info'],MANAGER_APPROVED:['معتمد من المدير','success'],HR_CLOSED:['مغلق من الموارد البشرية','success'],PRESENT:['حاضر','success'],LATE:['متأخر','warning'],ABSENT:['غائب','danger'],AUTO_CLOSED:['انصراف تلقائي','info'],INCOMPLETE:['غير مكتمل','danger'],CURRENT:['حالي','success'],HISTORY:['سجل سابق','muted'],OPEN:['مفتوح','info'],ON_TRACK:['يسير حسب الخطة','success'],AT_RISK:['يحتاج متابعة','warning'],ACHIEVED:['تم الإنجاز','success'],CANCELLED:['ملغى','muted'],IN_PROGRESS:['قيد التنفيذ','warning'],COMPLETED:['مكتمل','success'],DRAFT:['مسودة','muted'],DECIDED:['تم اتخاذ القرار','success'],CLOSED:['مغلق','muted'],UNDER_INVESTIGATION:['قيد التحقيق','warning'],PLANNED:['مخطط','info'],NEW:['جديد','info'],SCREENING:['فرز أولي','warning'],INTERVIEW:['مقابلة','info'],OFFER:['عرض وظيفي','info'],HIRED:['تم التعيين','success'],ON_HOLD:['معلّق','warning'],LOW:['منخفضة','muted'],NORMAL:['عادية','info'],HIGH:['عالية','warning'],CRITICAL:['حرجة','danger'],ASSIGNED:['مُسند','info'],OPENED:['مفتوح','info'],EARLY_DEPARTURE:['انصراف مبكر','warning']};const [label,kind]=map[value]||['غير محدد','muted'];return <span className={`status-badge ${kind}`}>{label}</span>}
export function Empty({text,action,onAction}:{text:string;action?:string;onAction?:()=>void}){return <div className="empty"><Icon name="search" size={26}/><strong>{text}</strong>{action&&<button className="secondary" onClick={onAction}>{action}</button>}</div>}
export function Skeleton({rows=5}:{rows?:number}){return <div className="skeleton-list" aria-label="جاري التحميل">{Array.from({length:rows}).map((_,i)=><div className="skeleton-row" key={i}><i/><span/><b/></div>)}</div>}
export function ErrorState({text,onRetry}:{text:string;onRetry?:()=>void}){return <div className="state-card error-state"><Icon name="alert" size={22}/><div><strong>تعذر تحميل البيانات</strong><span>{text}</span></div>{onRetry&&<button className="secondary" onClick={onRetry}>إعادة المحاولة</button>}</div>}
