export function Kpi({title,value,icon,danger}:{title:string;value:any;icon:string;danger?:boolean}){return <div className={`kpi ${danger?'danger-kpi':''}`}><div className="kpi-icon">{icon}</div><div><span>{title}</span><strong>{value}</strong></div><em>اليوم</em></div>}

export function Table({headers,rows}:{headers:string[];rows:any[][]}){return <>
  <div className="table-wrap hr-responsive-table"><table><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((v,j)=><td key={j} data-label={headers[j]}>{String(v??'—')}</td>)}</tr>)}</tbody></table></div>
  <div className="hr-mobile-records">{rows.map((r,i)=><article className="hr-mobile-record" key={`m-${i}`}><div className="hr-mobile-record-head"><strong>{String(r[0]??'—')}</strong><span>{String(r[headers.length-1]??'—')}</span></div>{r.slice(1,-1).map((v,j)=><div className="hr-mobile-field" key={j}><span>{headers[j+1]}</span><b>{String(v??'—')}</b></div>)}</article>)}</div>
  <style jsx global>{`
@media (max-width:800px){.hr-responsive-table{display:none!important}.hr-mobile-records{display:grid;gap:10px}.hr-mobile-record{background:#fff;border:1px solid #e5eaf2;border-radius:14px;padding:13px;box-shadow:0 6px 20px rgba(20,42,76,.05)}.hr-mobile-record-head{display:flex;justify-content:space-between;gap:10px;align-items:flex-start;padding-bottom:10px;margin-bottom:7px;border-bottom:1px solid #edf1f6}.hr-mobile-record-head strong{font-size:12px;line-height:1.6}.hr-mobile-record-head span{font-size:9px;color:#1769e0;background:#eef4ff;padding:5px 8px;border-radius:999px;white-space:nowrap}.hr-mobile-field{display:flex;justify-content:space-between;gap:12px;padding:7px 0;border-bottom:1px dashed #edf1f6;font-size:10px}.hr-mobile-field:last-child{border-bottom:0}.hr-mobile-field span{color:#8290a4}.hr-mobile-field b{font-weight:700;text-align:left;max-width:62%;overflow-wrap:anywhere}}@media (min-width:801px){.hr-mobile-records{display:none!important}}`}</style>
</>}

export function Empty({text}:{text:string}){return <div className="empty">{text}</div>}
