'use client';
import { useMemo, useState } from 'react';
import type { Employee, Project, Shift } from './types';
import { Badge } from './common';
import { Detail, Drawer, Filters, Metric, PageHeader, TableShell } from './ui';
export default function Employees({employees,projects,shifts,managerMode,employeeForm,setEmployeeForm,createEmployee,selectedEmployee,setSelectedEmployee,selectedProject,setSelectedProject,selectedShift,setSelectedShift,assignProject,busy,onEdit,onOpenProfile}:{employees:Employee[];projects:Project[];shifts:Shift[];managerMode:boolean;employeeForm:any;setEmployeeForm:any;createEmployee:()=>void;selectedEmployee:string;setSelectedEmployee:(v:string)=>void;selectedProject:string;setSelectedProject:(v:string)=>void;selectedShift:string;setSelectedShift:(v:string)=>void;assignProject:()=>void;busy:boolean;onEdit?:(id:string)=>void;onOpenProfile?:(id:string)=>void}){
 const es=Array.isArray(employees)?employees:[],ps=Array.isArray(projects)?projects:[],ss=Array.isArray(shifts)?shifts:[];const[q,setQ]=useState('');const[status,setStatus]=useState('ALL');const[selected,setSelected]=useState<Employee|null>(null);const filtered=useMemo(()=>es.filter(e=>(!q||`${e.name} ${e.employee_id} ${e.job_title||''} ${e.department||''}`.toLowerCase().includes(q.toLowerCase()))&&(status==='ALL'||(e.status||'ACTIVE')===status)),[es,q,status]);
 return <section className="panel page-panel"><PageHeader title="الموظفون" subtitle="ملفات الموظفين والتعيينات والورديات من مكان واحد." eyebrow="إدارة الموظفين" count={<span className="count-pill">{es.length} موظف</span>}/>
 <div className="ux-metric-grid"><Metric label="إجمالي الموظفين" value={es.length} icon="users"/><Metric label="على رأس العمل" value={es.filter(e=>(e.status||'ACTIVE')==='ACTIVE').length} tone="green" icon="check"/><Metric label="غير معينين" value={es.filter(e=>!e.project_id).length} tone="amber" icon="projects"/><Metric label="بدون وردية" value={es.filter(e=>!e.shift_id).length} tone="red" icon="shifts"/></div>
 {!managerMode&&<div className="ux-card" style={{marginBottom:14}}><div className="request-card-headline"><div><h3>إضافة موظف جديد</h3><p>أدخل البيانات الأساسية ثم اربطه بالمشروع والوردية الحالية.</p></div></div><div className="ux-grid-2"><label className="ux-field"><span>الاسم بالكامل *</span><input value={employeeForm.name} onChange={e=>setEmployeeForm({...employeeForm,name:e.target.value})}/></label><label className="ux-field"><span>المسمى الوظيفي *</span><input value={employeeForm.job_title} onChange={e=>setEmployeeForm({...employeeForm,job_title:e.target.value})}/></label><label className="ux-field"><span>القسم</span><input value={employeeForm.department} onChange={e=>setEmployeeForm({...employeeForm,department:e.target.value})}/></label><label className="ux-field"><span>الهاتف</span><input value={employeeForm.phone} onChange={e=>setEmployeeForm({...employeeForm,phone:e.target.value})}/></label><label className="ux-field"><span>الرقم القومي</span><input value={employeeForm.national_id} onChange={e=>setEmployeeForm({...employeeForm,national_id:e.target.value})}/></label><label className="ux-field"><span>تاريخ التعيين</span><input type="date" value={employeeForm.hire_date} onChange={e=>setEmployeeForm({...employeeForm,hire_date:e.target.value})}/></label><label className="ux-field"><span>نوع الموظف</span><select value={employeeForm.residency_type||'RESIDENT'} onChange={e=>setEmployeeForm({...employeeForm,residency_type:e.target.value})}><option value="RESIDENT">مقيم</option><option value="EXPATRIATE">مغترب</option></select></label><label className="ux-field"><span>المشروع الحالي *</span><select value={employeeForm.project_id} onChange={e=>setEmployeeForm({...employeeForm,project_id:e.target.value})}><option value="">اختر المشروع</option>{ps.map(p=><option key={p.project_id} value={p.project_id}>{p.name}</option>)}</select></label><label className="ux-field"><span>الوردية *</span><select value={employeeForm.shift_id} onChange={e=>setEmployeeForm({...employeeForm,shift_id:e.target.value})}><option value="">اختر الوردية</option>{ss.map(s=><option key={s.shift_id} value={s.shift_id}>{s.name}</option>)}</select></label></div><button className="primary" onClick={createEmployee} disabled={busy||!employeeForm.name||!employeeForm.job_title||!employeeForm.project_id||!employeeForm.shift_id}>تسجيل الموظف</button></div>}
 <div className="ux-card" style={{marginBottom:14}}><h3>نقل موظف وتغيير الوردية</h3><div className="ux-grid-2"><label className="ux-field"><span>الموظف</span><select value={selectedEmployee} onChange={e=>setSelectedEmployee(e.target.value)}><option value="">اختر الموظف</option>{es.map(e=><option key={e.employee_id} value={e.employee_id}>{e.name}</option>)}</select></label><label className="ux-field"><span>المشروع</span><select value={selectedProject} onChange={e=>setSelectedProject(e.target.value)}><option value="">اختر المشروع</option>{ps.map(p=><option key={p.project_id} value={p.project_id}>{p.name}</option>)}</select></label><label className="ux-field"><span>الوردية</span><select value={selectedShift} onChange={e=>setSelectedShift(e.target.value)}><option value="">اختر الوردية</option>{ss.map(s=><option key={s.shift_id} value={s.shift_id}>{s.name}</option>)}</select></label></div><button className="secondary" disabled={busy||!selectedEmployee||!selectedProject||!selectedShift} onClick={assignProject}>حفظ التعيين الجديد</button></div>
 <Filters onReset={()=>{setQ('');setStatus('ALL')}}><label className="ux-field"><span>بحث</span><input value={q} onChange={e=>setQ(e.target.value)} placeholder="اسم أو رقم وظيفي أو وظيفة"/></label><label className="ux-field"><span>الحالة</span><select value={status} onChange={e=>setStatus(e.target.value)}><option value="ALL">كل الحالات</option><option value="ACTIVE">نشط</option><option value="INACTIVE">غير نشط</option></select></label></Filters>
 <TableShell title="قائمة الموظفين" count={`${filtered.length} نتيجة`} empty={!filtered.length?'لا توجد سجلات مطابقة.':undefined}><table><thead><tr><th>الموظف</th><th>الوظيفة</th><th>القسم</th><th>المشروع</th><th>الوردية</th><th>الحالة</th><th>إجراء</th></tr></thead><tbody>{filtered.map(e=><tr key={e.employee_id} onClick={()=>setSelected(e)}><td><div className="ux-person"><span className="ux-avatar">{String(e.name||'?').charAt(0)}</span><span><strong>{e.name}</strong><small>{e.employee_id}</small></span></div></td><td>{e.job_title||'—'}</td><td>{e.department||'—'}</td><td>{e.current_project_name||e.project_name||'غير معين'}</td><td>{e.shift_name||'غير معين'}</td><td><Badge status={e.status||'ACTIVE'}/></td><td><div className="ux-action-row">{onOpenProfile&&<button className="secondary" onClick={ev=>{ev.stopPropagation();onOpenProfile(e.employee_id)}}>الملف</button>}{onEdit&&<button className="secondary" onClick={ev=>{ev.stopPropagation();onEdit(e.employee_id)}}>تعديل</button>}</div></td></tr>)}</tbody></table></TableShell>
 <Drawer open={!!selected} title={selected?.name||'بيانات الموظف'} subtitle={selected?.employee_id} onClose={()=>setSelected(null)} footer={selected&&<>{onOpenProfile&&<button className="secondary" onClick={()=>{onOpenProfile(selected.employee_id);setSelected(null)}}>فتح الملف الكامل</button>}{onEdit&&<button className="primary" onClick={()=>{onEdit(selected.employee_id);setSelected(null)}}>تعديل البيانات</button>}</>}><div className="ux-detail-grid"><Detail label="الوظيفة" value={selected?.job_title}/><Detail label="القسم" value={selected?.department}/><Detail label="الهاتف" value={selected?.phone}/><Detail label="نوع الموظف" value={selected?.residency_type==='EXPATRIATE'?'مغترب':'مقيم'}/><Detail label="المشروع" value={selected?.current_project_name||selected?.project_name}/><Detail label="الوردية" value={selected?.shift_name}/><Detail label="الحالة"><Badge status={selected?.status||'ACTIVE'}/></Detail></div></Drawer>
 </section>
}
