'use client';
import { useEffect, useState } from 'react';
import { api } from '@/lib/api';

type Props={employees:any[];role:string};
const tabs=[['disciplinary','الجزاءات'],['training','التدريب والتطوير'],['recruitment','التوظيف'],['workforce','تخطيط الاحتياج'],['payroll','تكامل الرواتب']];
const statusText:any={OPEN:'مفتوح',UNDER_INVESTIGATION:'قيد التحقيق',DECIDED:'تم اتخاذ القرار',CLOSED:'مغلق',CANCELLED:'ملغى',PLANNED:'مخطط',IN_PROGRESS:'قيد التنفيذ',COMPLETED:'مكتمل',NEW:'جديد',SCREENING:'فرز أولي',INTERVIEW:'مقابلة',OFFER:'عرض وظيفي',HIRED:'تم التعيين',REJECTED:'مرفوض',DRAFT:'مسودة',APPROVED:'معتمد',ACTIVE:'نشط',ON_HOLD:'معلّق',LOW:'منخفضة',NORMAL:'عادية',HIGH:'عالية',CRITICAL:'حرجة',ASSIGNED:'مُسند',HR_CLOSED:'مغلق من الموارد البشرية',MANAGER_APPROVED:'معتمد من المدير'};
const categoryText:any={ABSENCE:'غياب',LATE:'تأخير',EARLY_DEPARTURE:'انصراف مبكر',MISCONDUCT:'سلوك وظيفي',SAFETY:'سلامة',INSUBORDINATION:'عدم انضباط',PERFORMANCE:'أداء',OTHER:'أخرى'};
const badge=(s:string)=> <span className="status-badge info">{statusText[s]||s||'غير محدد'}</span>;
export default function HRAdvanced({employees}:Props){
 const [tab,setTab]=useState('disciplinary'); const [data,setData]=useState<any>({}); const [busy,setBusy]=useState(false); const [message,setMessage]=useState('');
 const [disc,setDisc]=useState({employee_id:'',incident_date:new Date().toISOString().slice(0,10),category:'OTHER',description:''});
 const [train,setTrain]=useState({name:'',provider:'',start_date:new Date().toISOString().slice(0,10),end_date:'',budget:'',target_roles:''});
 const [position,setPosition]=useState({title:'',department:'',project_id:'',headcount:'1',priority:'NORMAL'});
 const [candidate,setCandidate]=useState({position_id:'',name:'',phone:'',email:'',source:''});
 const [plan,setPlan]=useState({title:'',department:'',project_id:'',period_start:new Date().toISOString().slice(0,10),period_end:'',current_headcount:String(employees.length),required_headcount:''});
 const load=async(t=tab)=>{setBusy(true);setMessage('');try{const actions:any={disciplinary:'disciplinary_cases',training:'training_programs',recruitment:'recruitment_data',workforce:'workforce_plan'}; if(actions[t]) setData(await api(actions[t],{})); else setData({});}catch(e:any){setMessage(e?.message||'تعذر تحميل البيانات')}finally{setBusy(false)}};
 useEffect(()=>{void load(tab)},[tab]);
 const create=async(action:string,body:any)=>{setBusy(true);try{await api(action,body);setMessage('تم الحفظ بنجاح');await load(tab)}catch(e:any){setMessage(e?.message||'تعذر الحفظ')}finally{setBusy(false)}};
 const employeeName=(id:string)=>employees.find(e=>e.employee_id===id)?.name||id;
 return <section className="panel-section">
  <div className="section-head"><div><h2>إدارة الموارد البشرية المتقدمة</h2><p>الجزاءات والتطوير والتوظيف وتخطيط الاحتياج وتكامل الرواتب.</p></div></div>
  <div className="tab-strip">{tabs.map(([id,label])=><button key={id} className={tab===id?'tab active':'tab'} onClick={()=>setTab(id)}>{label}</button>)}</div>
  {message&&<div className="alert success">{message}</div>}
  {busy&&<div className="state-card"><strong>جاري التحميل...</strong></div>}

  {tab==='disciplinary'&&<div className="advanced-grid">
    <div className="request-card"><h3>فتح حالة تأديبية</h3><div className="formgrid">
      <label><span>الموظف</span><select value={disc.employee_id} onChange={e=>setDisc({...disc,employee_id:e.target.value})}><option value="">اختر الموظف</option>{employees.map(e=><option key={e.employee_id} value={e.employee_id}>{e.name}</option>)}</select></label>
      <label><span>التاريخ</span><input type="date" value={disc.incident_date} onChange={e=>setDisc({...disc,incident_date:e.target.value})}/></label>
      <label><span>التصنيف</span><select value={disc.category} onChange={e=>setDisc({...disc,category:e.target.value})}>{Object.entries(categoryText).map(([k,v])=><option key={k} value={k}>{v as string}</option>)}</select></label>
      <label><span>وصف الواقعة</span><textarea value={disc.description} onChange={e=>setDisc({...disc,description:e.target.value})}/></label>
    </div><button className="primary" disabled={!disc.employee_id||!disc.description} onClick={()=>create('create_disciplinary_case',disc)}>حفظ الحالة</button></div>
    <div className="table-wrap"><table><thead><tr><th>الموظف</th><th>التاريخ</th><th>التصنيف</th><th>الحالة</th><th>إجراء</th></tr></thead><tbody>{(data||[]).map((r:any)=><tr key={r.case_id}><td>{r.employees?.name||employeeName(r.employee_id)}</td><td>{r.incident_date}</td><td>{categoryText[r.category]||r.category}</td><td>{badge(r.status)}</td><td>{['OPEN','UNDER_INVESTIGATION'].includes(r.status)?<button className="tiny secondary" onClick={()=>create('decide_disciplinary_case',{case_id:r.case_id,status:r.status==='OPEN'?'UNDER_INVESTIGATION':'DECIDED',resolution:''})}>{r.status==='OPEN'?'بدء التحقيق':'اتخاذ القرار'}</button>: '—'}</td></tr>)}</tbody></table></div>
  </div>}

  {tab==='training'&&<div className="advanced-grid">
    <div className="request-card"><h3>إضافة برنامج تدريب</h3><div className="formgrid">
      <label><span>اسم البرنامج</span><input value={train.name} onChange={e=>setTrain({...train,name:e.target.value})}/></label><label><span>الجهة</span><input value={train.provider} onChange={e=>setTrain({...train,provider:e.target.value})}/></label><label><span>البداية</span><input type="date" value={train.start_date} onChange={e=>setTrain({...train,start_date:e.target.value})}/></label><label><span>النهاية</span><input type="date" value={train.end_date} onChange={e=>setTrain({...train,end_date:e.target.value})}/></label></div><button className="primary" disabled={!train.name} onClick={()=>create('create_training_program',{...train,budget:train.budget?Number(train.budget):0})}>حفظ البرنامج</button></div>
    <div className="table-wrap"><table><thead><tr><th>البرنامج</th><th>الجهة</th><th>البداية</th><th>الحالة</th></tr></thead><tbody>{(data||[]).map((r:any)=><tr key={r.program_id}><td>{r.name}</td><td>{r.provider||'—'}</td><td>{r.start_date}</td><td>{badge(r.status)}</td></tr>)}</tbody></table></div>
  </div>}

  {tab==='recruitment'&&<div className="advanced-grid">
    <div className="request-card"><h3>إضافة شاغر</h3><div className="formgrid"><label><span>المسمى الوظيفي</span><input value={position.title} onChange={e=>setPosition({...position,title:e.target.value})}/></label><label><span>الإدارة</span><input value={position.department} onChange={e=>setPosition({...position,department:e.target.value})}/></label><label><span>عدد الشواغر</span><input type="number" min="1" value={position.headcount} onChange={e=>setPosition({...position,headcount:e.target.value})}/></label><label><span>الأولوية</span><select value={position.priority} onChange={e=>setPosition({...position,priority:e.target.value})}><option value="LOW">منخفضة</option><option value="NORMAL">عادية</option><option value="HIGH">عالية</option><option value="CRITICAL">حرجة</option></select></label></div><button className="primary" disabled={!position.title} onClick={()=>create('create_recruitment_position',{...position,headcount:Number(position.headcount)})}>حفظ الشاغر</button></div>
    <div className="request-card"><h3>إضافة مرشح</h3><div className="formgrid"><label><span>الشاغر</span><select value={candidate.position_id} onChange={e=>setCandidate({...candidate,position_id:e.target.value})}><option value="">اختر الشاغر</option>{(data?.positions||[]).map((r:any)=><option key={r.position_id} value={r.position_id}>{r.title}</option>)}</select></label><label><span>الاسم</span><input value={candidate.name} onChange={e=>setCandidate({...candidate,name:e.target.value})}/></label><label><span>الهاتف</span><input value={candidate.phone} onChange={e=>setCandidate({...candidate,phone:e.target.value})}/></label><label><span>البريد</span><input value={candidate.email} onChange={e=>setCandidate({...candidate,email:e.target.value})}/></label></div><button className="primary" disabled={!candidate.position_id||!candidate.name||!candidate.phone} onClick={()=>create('add_recruitment_candidate',candidate)}>حفظ المرشح</button></div>
    <div className="table-wrap"><table><thead><tr><th>الشاغر</th><th>العدد</th><th>المشغول</th><th>الأولوية</th><th>الحالة</th></tr></thead><tbody>{(data?.positions||[]).map((r:any)=><tr key={r.position_id}><td>{r.title}</td><td>{r.headcount}</td><td>{r.filled_count}</td><td>{statusText[r.priority]||r.priority}</td><td>{statusText[r.status]||r.status}</td></tr>)}</tbody></table></div>
    <div className="table-wrap"><table><thead><tr><th>المرشح</th><th>الهاتف</th><th>الحالة</th></tr></thead><tbody>{(data?.candidates||[]).map((r:any)=><tr key={r.candidate_id}><td>{r.name}</td><td>{r.phone}</td><td>{badge(r.status)}</td></tr>)}</tbody></table></div>
  </div>}

  {tab==='workforce'&&<div className="advanced-grid">
    <div className="request-card"><h3>خطة احتياج الموارد البشرية</h3><div className="formgrid"><label><span>عنوان الخطة</span><input value={plan.title} onChange={e=>setPlan({...plan,title:e.target.value})}/></label><label><span>الإدارة</span><input value={plan.department} onChange={e=>setPlan({...plan,department:e.target.value})}/></label><label><span>بداية الفترة</span><input type="date" value={plan.period_start} onChange={e=>setPlan({...plan,period_start:e.target.value})}/></label><label><span>نهاية الفترة</span><input type="date" value={plan.period_end} onChange={e=>setPlan({...plan,period_end:e.target.value})}/></label><label><span>العدد الحالي</span><input type="number" min="0" value={plan.current_headcount} onChange={e=>setPlan({...plan,current_headcount:e.target.value})}/></label><label><span>العدد المطلوب</span><input type="number" min="0" value={plan.required_headcount} onChange={e=>setPlan({...plan,required_headcount:e.target.value})}/></label></div><button className="primary" disabled={!plan.title||!plan.required_headcount} onClick={()=>create('create_workforce_plan',{...plan,current_headcount:Number(plan.current_headcount),required_headcount:Number(plan.required_headcount)})}>حفظ الخطة</button></div>
    <div className="table-wrap"><table><thead><tr><th>الخطة</th><th>الحالي</th><th>المطلوب</th><th>الفجوة</th><th>الحالة</th></tr></thead><tbody>{(data||[]).map((r:any)=><tr key={r.plan_id}><td>{r.title}</td><td>{r.current_headcount}</td><td>{r.required_headcount}</td><td>{Number(r.required_headcount)-Number(r.current_headcount)}</td><td>{badge(r.status)}</td></tr>)}</tbody></table></div>
  </div>}

  {tab==='payroll'&&<div className="request-card"><h3>تكامل الرواتب</h3><p>تجهيز بيانات الحضور والإجازات والخصومات للتصدير إلى نظام الرواتب، بدون حساب صافي الراتب أو الضرائب أو التأمينات داخل ELNUBY HR.</p><div className="formgrid"><label><span>من</span><input id="payroll-start" type="date" defaultValue={new Date().toISOString().slice(0,8)+'01'}/></label><label><span>إلى</span><input id="payroll-end" type="date" defaultValue={new Date().toISOString().slice(0,10)}/></label></div><button className="primary" onClick={async()=>{const start=(document.getElementById('payroll-start') as HTMLInputElement).value;const end=(document.getElementById('payroll-end') as HTMLInputElement).value;try{const r=await api('payroll_export_preview',{start_date:start,end_date:end});setData(r);setMessage('تم تجهيز ملخص تكامل الرواتب')}catch(e:any){setMessage(e?.message||'تعذر تجهيز الملخص')}}}>تجهيز الملخص</button>{data?.rows&&<div className="table-wrap" style={{marginTop:16}}><table><thead><tr><th>الموظف</th><th>أيام الحضور</th><th>دقائق التأخير</th><th>أيام الإجازة</th><th>الخصومات</th></tr></thead><tbody>{data.rows.map((r:any)=><tr key={r.employee_id}><td>{r.name}</td><td>{r.days_present}</td><td>{r.late_minutes}</td><td>{r.approved_leave_days}</td><td>{r.deductions}</td></tr>)}</tbody></table></div>}</div>}
 </section>
}
