import { useEffect, useMemo, useState } from 'react';
import { api, apiMultipart } from '@/lib/api';
import { Empty, Badge } from './common';

type Props={rows:any[];role:string;employeeMode:boolean;leaveType:string;setLeaveType:(v:string)=>void;leaveFrom:string;setLeaveFrom:(v:string)=>void;leaveTo:string;setLeaveTo:(v:string)=>void;leaveReason:string;setLeaveReason:(v:string)=>void;createLeave:(document?:File)=>void;busy:boolean};
export default function LeaveSection(props:Props){
 const {rows,role,employeeMode,leaveType,setLeaveType,leaveFrom,setLeaveFrom,leaveTo,setLeaveTo,leaveReason,setLeaveReason,createLeave,busy}=props;
 const [medicalDocument,setMedicalDocument]=useState<File|null>(null); const [balances,setBalances]=useState<any[]>([]);
 const [me,setMe]=useState<any>(null); const [localRows,setLocalRows]=useState<any[]>(rows); const [employees,setEmployees]=useState<any[]>([]); const [projects,setProjects]=useState<any[]>([]); const [loadingDetails,setLoadingDetails]=useState(false);
 const manager=role==='PROJECT_MANAGER'||role==='SECTOR_MANAGER'; const hr=role==='HR_MANAGER'||role==='SYSTEM_ADMIN';
 useEffect(()=>{setLocalRows(Array.isArray(rows)?rows:[])},[rows]);
 useEffect(()=>{if(!employeeMode)return; void api<any[]>('leave_balances').then(setBalances).catch(()=>setBalances([]));},[employeeMode]);
 useEffect(()=>{let active=true;(async()=>{try{const mine=await api<any>('me');if(active)setMe(mine);if(['SYSTEM_ADMIN','HR_MANAGER','SECTOR_MANAGER','PROJECT_MANAGER'].includes(mine?.user?.role)){setLoadingDetails(true);const needsE=(Array.isArray(rows)?rows:[]).some(r=>!r.employee_name&&r.employee_id);const needsP=(Array.isArray(rows)?rows:[]).some(r=>!r.project_name&&r.project_id);const [es,ps]=await Promise.all([needsE?api<any[]>('employees'):Promise.resolve([]),needsP?api<any[]>('projects'):Promise.resolve([])]);if(active){setEmployees(es||[]);setProjects(ps||[]);}}}catch(e){console.error('leave lookup:',e)}finally{if(active)setLoadingDetails(false)}})();return()=>{active=false}},[rows]);
 const displayRows=useMemo(()=>{const em=new Map((Array.isArray(employees)?employees:[]).map(e=>[String(e.employee_id),e]));const pm=new Map((Array.isArray(projects)?projects:[]).map(p=>[String(p.project_id),p]));return (Array.isArray(localRows)?localRows:[]).map(r=>{const own=String(me?.user?.employee_id||'')===String(r.employee_id||'');const employee=em.get(String(r.employee_id))||(own?me?.employee:null);const ownProject=String(me?.project?.project_id||'')===String(r.project_id||'');const project=pm.get(String(r.project_id))||(ownProject?me?.project:null);return {...r,employee_name:r.employee_name||employee?.name||r.employee_id,job_title:r.job_title||employee?.job_title,department:r.department||employee?.department,employee_status:r.employee_status||employee?.status,project_name:r.project_name||project?.name||r.project_id};})},[localRows,employees,projects,me]);
 async function decide(action:'decide_leave_manager'|'decide_leave_hr',requestId:string,decision:'APPROVE'|'REJECT'){try{const result=await api(action,{request_id:requestId,decision});setLocalRows(prev=>prev.map(r=>r.request_id===requestId?{...r,status:action==='decide_leave_hr'?(decision==='APPROVE'?'APPROVED':'REJECTED'):(decision==='APPROVE'?'PENDING_HR':'REJECTED')}:r));window.dispatchEvent(new CustomEvent('hr:toast',{detail:{message:decision==='APPROVE'?'تم اعتماد طلب الإجازة':'تم رفض طلب الإجازة'}}));return result}catch(error:any){window.dispatchEvent(new CustomEvent('hr:toast',{detail:{message:error?.message||'تعذر تنفيذ القرار',type:'error'}}));}}
 return <section className="panel page-panel hr-leave"><div className="panel-head"><div><div className="eyebrow">LEAVE MANAGEMENT</div><h2>الإجازات</h2><p>بيانات الموظف والمشروع والرصيد مع مسار اعتماد واضح من مدير المشروع إلى HR.</p></div><div style={{display:'flex',gap:8,alignItems:'center'}}><span className="count-pill">{displayRows.length} طلب</span>{loadingDetails&&<span className="live">جاري تحديث البيانات</span>}</div></div>
 {employeeMode&&<div className="request-card hr-leave-form"><div className="hr-leave-form-head"><div><h3>طلب إجازة جديد</h3><p>اختر النوع والفترة والسبب. المرضية تحتاج مستندًا مؤيدًا.</p></div><span className="live">طلب جديد</span></div>
 <div className="formgrid"><label><span>نوع الإجازة</span><select value={leaveType} onChange={e=>{setLeaveType(e.target.value);setMedicalDocument(null)}}><option value="LT-ANNUAL">سنوية</option><option value="LT-CASUAL">عارضة</option><option value="LT-SICK">مرضية</option><option value="LT-UNPAID">بدون أجر</option></select></label><label><span>من</span><input type="date" value={leaveFrom} onChange={e=>setLeaveFrom(e.target.value)}/></label><label><span>إلى</span><input type="date" value={leaveTo} onChange={e=>setLeaveTo(e.target.value)}/></label><label><span>سبب الإجازة</span><input placeholder="اكتب سبب الإجازة" value={leaveReason} onChange={e=>setLeaveReason(e.target.value)}/></label>
 {leaveType==='LT-SICK'&&<label><span>المستند الطبي *</span><input type="file" accept=".pdf,.jpg,.jpeg,.png,.webp" onChange={e=>setMedicalDocument(e.target.files?.[0]||null)}/><small>PDF أو صورة — حتى 10 ميجابايت</small></label>}</div>
 {employeeMode&&balances.length>0&&<div className="leave-balance-strip">{balances.slice(0,3).map((b:any)=><div key={b.id}><span>{b.leave_types?.name||b.leave_type_id}</span><strong>{b.remaining} يوم</strong></div>)}</div>}
 <button className="primary" disabled={busy|| (leaveType==='LT-SICK'&&!medicalDocument)} onClick={()=>createLeave(medicalDocument||undefined)}>{busy?'جاري الإرسال...':'إرسال طلب الإجازة'}</button></div>}
 <div className="table-wrap hr-leave-table"><table><thead><tr>{['الموظف','الوظيفة','القسم','المشروع','النوع','من','إلى','الأيام','الرصيد','المستخدم','الحالة','إجراء'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{displayRows.map(r=><tr key={r.request_id}><td data-label="الموظف"><strong>{r.employee_name||r.employee_id||'غير محدد'}</strong><small>{r.employee_id||'—'}</small></td><td data-label="الوظيفة">{r.job_title||'غير محدد'}</td><td data-label="القسم">{r.department||'غير محدد'}</td><td data-label="المشروع">{r.project_name||r.project_id||'غير محدد'}</td><td data-label="النوع">{r.leave_type_name||r.leave_type_id||'غير محدد'}</td><td data-label="من">{r.from_date||'—'}</td><td data-label="إلى">{r.to_date||'—'}</td><td data-label="الأيام">{r.days??'—'}</td><td data-label="الرصيد">{r.leave_balance?.remaining??'غير متاح'}</td><td data-label="المستخدم">{r.leave_balance?.used??'—'}</td><td data-label="الحالة"><Badge status={r.status}/></td><td data-label="إجراء">{r.document_required&&<button className="tiny secondary" onClick={async()=>{try{const d=await api<any>('leave_document',{request_id:r.request_id});window.open(d.signed_url,'_blank','noopener,noreferrer')}catch(e:any){window.dispatchEvent(new CustomEvent('hr:toast',{detail:{message:e.message||'تعذر فتح المستند',type:'error'}}))}}}>المستند</button>}{manager&&r.status==='PENDING_MANAGER'&&<div style={{display:'flex',gap:5}}><button className="tiny approve" onClick={()=>void decide('decide_leave_manager',r.request_id,'APPROVE')}>اعتماد</button><button className="tiny reject" onClick={()=>void decide('decide_leave_manager',r.request_id,'REJECT')}>رفض</button></div>}{hr&&r.status==='PENDING_HR'&&<div style={{display:'flex',gap:5}}><button className="tiny approve" onClick={()=>void decide('decide_leave_hr',r.request_id,'APPROVE')}>اعتماد HR</button><button className="tiny reject" onClick={()=>void decide('decide_leave_hr',r.request_id,'REJECT')}>رفض</button></div>}</td></tr>)}</tbody></table></div>{!displayRows.length&&<Empty text="لا توجد طلبات إجازة."/>}
</section>;
}
