import { useEffect, useMemo, useState } from 'react';
import { api } from '@/lib/api';
import { Empty } from './common';

type Props={rows:any[];role:string;employeeMode:boolean;leaveType:string;setLeaveType:(v:string)=>void;leaveFrom:string;setLeaveFrom:(v:string)=>void;leaveTo:string;setLeaveTo:(v:string)=>void;leaveReason:string;setLeaveReason:(v:string)=>void;createLeave:()=>void;busy:boolean};
export default function LeaveSection(props:Props){
 const {rows,role,employeeMode,leaveType,setLeaveType,leaveFrom,setLeaveFrom,leaveTo,setLeaveTo,leaveReason,setLeaveReason,createLeave,busy}=props;
 const [me,setMe]=useState<any>(null); const [employees,setEmployees]=useState<any[]>([]); const [projects,setProjects]=useState<any[]>([]); const [loadingDetails,setLoadingDetails]=useState(false);
 const manager=role==='PROJECT_MANAGER'||role==='SECTOR_MANAGER'; const hr=role==='HR_MANAGER'||role==='SYSTEM_ADMIN';
 useEffect(()=>{let active=true;(async()=>{try{const mine=await api<any>('me');if(active)setMe(mine);if(['SYSTEM_ADMIN','HR_MANAGER','SECTOR_MANAGER','PROJECT_MANAGER'].includes(mine?.user?.role)){setLoadingDetails(true);const needsE=rows.some(r=>!r.employee_name&&r.employee_id);const needsP=rows.some(r=>!r.project_name&&r.project_id);const [es,ps]=await Promise.all([needsE?api<any[]>('employees'):Promise.resolve([]),needsP?api<any[]>('projects'):Promise.resolve([])]);if(active){setEmployees(es||[]);setProjects(ps||[]);}}}catch(e){console.error('leave lookup:',e)}finally{if(active)setLoadingDetails(false)}})();return()=>{active=false}},[rows]);
 const displayRows=useMemo(()=>{const em=new Map(employees.map(e=>[String(e.employee_id),e]));const pm=new Map(projects.map(p=>[String(p.project_id),p]));return rows.map(r=>{const own=String(me?.user?.employee_id||'')===String(r.employee_id||'');const employee=em.get(String(r.employee_id))||(own?me?.employee:null);const ownProject=String(me?.project?.project_id||'')===String(r.project_id||'');const project=pm.get(String(r.project_id))||(ownProject?me?.project:null);return {...r,employee_name:r.employee_name||employee?.name||r.employee_id,job_title:r.job_title||employee?.job_title,department:r.department||employee?.department,employee_status:r.employee_status||employee?.status,project_name:r.project_name||project?.name||r.project_id};})},[rows,employees,projects,me]);
 async function decide(action:'decide_leave_manager'|'decide_leave_hr',requestId:string,decision:'APPROVE'|'REJECT'){try{await api(action,{request_id:requestId,decision});location.reload()}catch(error:any){alert(error?.message||'تعذر تنفيذ القرار')}}
 return <section className="panel page-panel hr-leave"><div className="panel-head"><div><div className="eyebrow">LEAVE MANAGEMENT</div><h2>الإجازات</h2><p>بيانات الموظف والمشروع والرصيد مع مسار اعتماد واضح من مدير المشروع إلى HR.</p></div><div style={{display:'flex',gap:8,alignItems:'center'}}><span className="count-pill">{displayRows.length} طلب</span>{loadingDetails&&<span className="live">جاري تحديث البيانات</span>}</div></div>
 {employeeMode&&<div className="request-card hr-leave-form"><div className="hr-leave-form-head"><div><h3>طلب إجازة جديد</h3><p>حدد النوع والفترة والسبب ثم أرسل الطلب للاعتماد.</p></div><span className="live">طلب جديد</span></div><div className="formgrid"><select value={leaveType} onChange={e=>setLeaveType(e.target.value)}><option value="LT-ANNUAL">سنوية</option><option value="LT-CASUAL">عارضة</option><option value="LT-SICK">مرضية</option><option value="LT-UNPAID">بدون أجر</option><option value="LT-OTHER">أخرى</option></select><label><span>من</span><input type="date" value={leaveFrom} onChange={e=>setLeaveFrom(e.target.value)}/></label><label><span>إلى</span><input type="date" value={leaveTo} onChange={e=>setLeaveTo(e.target.value)}/></label><label><span>سبب الإجازة</span><input placeholder="اكتب سبب الإجازة" value={leaveReason} onChange={e=>setLeaveReason(e.target.value)}/></label></div><button className="primary" disabled={busy} onClick={createLeave}>{busy?'جاري الإرسال...':'إرسال طلب الإجازة'}</button></div>}
 <div className="table-wrap hr-leave-table"><table><thead><tr>{['الموظف','الوظيفة','القسم','المشروع','النوع','من','إلى','الأيام','الرصيد','المعلق','المستخدم','الحالة','إجراء'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{displayRows.map(r=><tr key={r.request_id}><td data-label="الموظف"><strong>{r.employee_name||r.employee_id||'غير محدد'}</strong><small>{r.employee_id||'—'}</small></td><td data-label="الوظيفة">{r.job_title||'غير محدد'}</td><td data-label="القسم">{r.department||'غير محدد'}</td><td data-label="المشروع">{r.project_name||r.project_id||'غير محدد'}</td><td data-label="النوع">{r.leave_type_name||r.leave_type_id||'غير محدد'}</td><td data-label="من">{r.from_date||'—'}</td><td data-label="إلى">{r.to_date||'—'}</td><td data-label="الأيام">{r.days??'—'}</td><td data-label="الرصيد">{r.leave_balance?.remaining??'غير متاح'}</td><td data-label="المعلق">{r.leave_balance?.pending??'—'}</td><td data-label="المستخدم">{r.leave_balance?.used??'—'}</td><td data-label="الحالة"><span className={r.status==='APPROVED'?'live':r.status==='REJECTED'?'alert danger':'count-pill'}>{r.status||'غير محدد'}</span></td><td data-label="إجراء">{manager&&r.status==='PENDING_MANAGER'&&<div style={{display:'flex',gap:5}}><button className="tiny approve" onClick={()=>void decide('decide_leave_manager',r.request_id,'APPROVE')}>اعتماد</button><button className="tiny reject" onClick={()=>void decide('decide_leave_manager',r.request_id,'REJECT')}>رفض</button></div>}{hr&&r.status==='PENDING_HR'&&<div style={{display:'flex',gap:5}}><button className="tiny approve" onClick={()=>void decide('decide_leave_hr',r.request_id,'APPROVE')}>اعتماد HR</button><button className="tiny reject" onClick={()=>void decide('decide_leave_hr',r.request_id,'REJECT')}>رفض</button></div>}</td></tr>)}</tbody></table></div>{!displayRows.length&&<Empty text="لا توجد طلبات إجازة."/>}
 <style jsx global>{`
.hr-leave-form-head{display:flex;justify-content:space-between;gap:10px;align-items:flex-start;margin-bottom:13px}.hr-leave-form-head h3{margin:0;font-size:14px}.hr-leave-form-head p{margin:4px 0 0;color:#8290a4;font-size:10px}.hr-leave-form label{display:block}.hr-leave-form label>span{display:block;color:#718096;font-size:9px;margin:0 0 5px}.hr-leave-form .formgrid{align-items:end}@media(max-width:800px){.hr-leave-form .formgrid{grid-template-columns:1fr}.hr-leave-form .primary{width:100%}.hr-leave-table{border:0;overflow:visible}.hr-leave-table table{min-width:0;border:0}.hr-leave-table thead{display:none}.hr-leave-table tbody{display:grid;gap:10px}.hr-leave-table tr{display:block;border:1px solid #e5eaf2;border-radius:14px;background:#fff;padding:11px;box-shadow:0 6px 20px rgba(20,42,76,.05)}.hr-leave-table td{display:flex;justify-content:space-between;gap:12px;align-items:flex-start;padding:8px 2px;border-bottom:1px dashed #edf1f6;white-space:normal;font-size:10px}.hr-leave-table td:last-child{border-bottom:0}.hr-leave-table td:before{content:attr(data-label);color:#8290a4;font-weight:700}.hr-leave-table td>strong{display:block}.hr-leave-table td>small{display:block;color:#98a3b3;margin-top:2px}.hr-leave-table td>span{margin-right:auto}}`}</style></section>;
}
