'use client';
import { useEffect, useMemo, useState } from 'react';
import { api } from '@/lib/api';
import { Badge, employeeName } from './common';
import { ConfirmDialog, Detail, Drawer, Filters, Metric, PageHeader, TableShell } from './ui';

const types=[['LT-ANNUAL','سنوية','للرصيد السنوي'],['LT-CASUAL','عارضة','للحالات الطارئة القصيرة'],['LT-SICK','مرضية','تحتاج مستندًا مؤيدًا'],['LT-UNPAID','بدون أجر','وفق موافقة الإدارة']];
const typeName=(v:string)=>types.find(x=>x[0]===v)?.[1]||v||'غير محدد';
function daysBetween(a:string,b:string){if(!a||!b)return 0;const d1=new Date(`${a}T00:00:00`),d2=new Date(`${b}T00:00:00`);return d2<d1?0:Math.floor((d2.getTime()-d1.getTime())/86400000)+1}
export default function LeaveSection({rows,role,employeeMode,leaveType,setLeaveType,leaveFrom,setLeaveFrom,leaveTo,setLeaveTo,leaveReason,setLeaveReason,createLeave,busy}:any){
 const safeRows=Array.isArray(rows)?rows:[]; const [local,setLocal]=useState<any[]>(safeRows);const [medicalDocument,setMedicalDocument]=useState<File|null>(null);const [balances,setBalances]=useState<any[]>([]);const [employees,setEmployees]=useState<any[]>([]);const [q,setQ]=useState('');const[status,setStatus]=useState('ALL');const[selected,setSelected]=useState<any>(null);const[reject,setReject]=useState<any>(null);
 useEffect(()=>setLocal(Array.isArray(rows)?rows:[]),[rows]); useEffect(()=>{let active=true; (async()=>{try{const r=await api<any[]>('employees');if(active)setEmployees(Array.isArray(r)?r:[])}catch{if(active)setEmployees([])}})();return()=>{active=false}},[]); useEffect(()=>{if(employeeMode)void api<any[]>('leave_balances').then(x=>setBalances(Array.isArray(x)?x:[])).catch(()=>setBalances([]))},[employeeMode]);
 const filtered=useMemo(()=>local.filter(r=>(!q||`${r.employee_name||''} ${r.employee_id||''}`.toLowerCase().includes(q.toLowerCase()))&&(status==='ALL'||r.status===status)),[local,q,status]);
 const requestDays=daysBetween(leaveFrom,leaveTo); const balance=balances.find(b=>String(b.leave_type_id)===String(leaveType)); const after=balance?Number(balance.remaining||0)-requestDays:null;
 const decide=async(requestId:string,decision:'APPROVE'|'REJECT',comment?:string)=>{const action=role==='HR_MANAGER'||role==='SYSTEM_ADMIN'?'decide_leave_hr':'decide_leave_manager';try{await api(action,{request_id:requestId,decision,comment});setLocal(prev=>prev.map(r=>r.request_id===requestId?{...r,status:decision==='REJECT'?'REJECTED':action==='decide_leave_hr'?'APPROVED':'PENDING_HR'}:r));setReject(null)}catch(e:any){window.dispatchEvent(new CustomEvent('hr:toast',{detail:{message:e?.message||'تعذر تنفيذ القرار',type:'error'}}))}};
 const canDecide=['PROJECT_MANAGER','SECTOR_MANAGER'].includes(role); const canHR=['HR_MANAGER','SYSTEM_ADMIN'].includes(role);
 return <section className="panel page-panel"><PageHeader title="الإجازات" subtitle="تقديم ومراجعة الإجازات مع الرصيد ومسار الاعتماد في مكان واحد." eyebrow="طلبات الموظفين" count={<span className="count-pill">{filtered.length} طلب</span>}/>
 {employeeMode&&<div className="ux-card" style={{marginBottom:14}}><div className="request-card-headline"><div><h3>طلب إجازة جديد</h3><p>اختر النوع والفترة، ثم راجع المدة والرصيد قبل الإرسال.</p></div><span className="status-badge info">طلب جديد</span></div><div className="permission-type-grid">{types.map(t=><button type="button" key={t[0]} className={`permission-type-option ${leaveType===t[0]?'active':''}`} onClick={()=>{setLeaveType(t[0]);setMedicalDocument(null)}}><strong>{t[1]}</strong><span>{t[2]}</span></button>)}</div><div className="ux-grid-2"><label className="ux-field"><span>من</span><input type="date" value={leaveFrom} onChange={e=>setLeaveFrom(e.target.value)}/></label><label className="ux-field"><span>إلى</span><input type="date" value={leaveTo} min={leaveFrom||undefined} onChange={e=>setLeaveTo(e.target.value)}/></label><label className="ux-field"><span>السبب</span><textarea value={leaveReason} onChange={e=>setLeaveReason(e.target.value)} rows={3} placeholder="اكتب سبب الإجازة"/></label>{leaveType==='LT-SICK'&&<label className="ux-field"><span>المستند الطبي *</span><input id="leave-medical-document" type="file" accept=".pdf,.jpg,.jpeg,.png,.webp" onChange={e=>setMedicalDocument(e.target.files?.[0]||null)}/><small>يمكن إرفاقه عند الإرسال حسب سياسة الشركة.</small></label>}</div><div className="leave-summary-strip"><div><span>مدة الطلب</span><strong>{requestDays||0} يوم</strong></div><div><span>الرصيد الحالي</span><strong>{balance?`${balance.remaining} يوم`:'غير متاح'}</strong></div><div><span>الرصيد بعد الطلب</span><strong className={after!==null&&after<0?'text-danger':''}>{after===null?'غير متاح':`${Math.max(after,0)} يوم`}</strong></div></div><button className="primary" disabled={busy||!leaveFrom||!leaveTo||!leaveReason||requestDays<1||(leaveType==='LT-SICK'&&!medicalDocument)} onClick={()=>{const f=(document.getElementById('leave-medical-document') as HTMLInputElement|undefined)?.files?.[0];createLeave(f || undefined)}}>{busy?'جاري الإرسال...':'إرسال طلب الإجازة'}</button></div>}
 <Filters onReset={()=>{setQ('');setStatus('ALL')}}><label className="ux-field"><span>بحث</span><input value={q} onChange={e=>setQ(e.target.value)} placeholder="اسم الموظف أو الرقم الوظيفي"/></label><label className="ux-field"><span>الحالة</span><select value={status} onChange={e=>setStatus(e.target.value)}><option value="ALL">كل الحالات</option><option value="PENDING_MANAGER">بانتظار المدير</option><option value="PENDING_HR">بانتظار الموارد البشرية</option><option value="APPROVED">معتمد</option><option value="REJECTED">مرفوض</option></select></label></Filters>
 <TableShell title="طلبات الإجازات" count={`${filtered.length} نتيجة`} empty={!filtered.length?'لا توجد طلبات إجازة مطابقة.':undefined}><table><thead><tr><th>الموظف</th><th>النوع</th><th>الفترة</th><th>المدة</th><th>الرصيد</th><th>الحالة</th><th>الإجراء</th></tr></thead><tbody>{filtered.map(r=><tr key={r.request_id} onClick={()=>setSelected(r)}><td><div className="ux-person"><span className="ux-avatar">{employeeName(r, employees).charAt(0)}</span><span><strong>{employeeName(r, employees)}</strong><small>{r.employee_id||'—'}</small></span></div></td><td>{r.leave_type_name||typeName(r.leave_type_id)}</td><td>{r.from_date||'—'} — {r.to_date||'—'}</td><td>{r.days??daysBetween(r.from_date,r.to_date)} يوم</td><td>{r.leave_balance?.remaining??'—'} يوم</td><td><Badge status={r.status}/></td><td><div className="ux-action-row">{canDecide&&r.status==='PENDING_MANAGER'&&<><button className="secondary" onClick={e=>{e.stopPropagation();void decide(r.request_id,'APPROVE')}} disabled={busy}>اعتماد</button><button className="danger-outline" onClick={e=>{e.stopPropagation();setReject(r)}} disabled={busy}>رفض</button></>}{canHR&&r.status==='PENDING_HR'&&<><button className="secondary" onClick={e=>{e.stopPropagation();void decide(r.request_id,'APPROVE')}} disabled={busy}>اعتماد نهائي</button><button className="danger-outline" onClick={e=>{e.stopPropagation();setReject(r)}} disabled={busy}>رفض</button></>}</div></td></tr>)}</tbody></table></TableShell>
 <Drawer open={!!selected} title="تفاصيل طلب الإجازة" subtitle={selected?.request_id} onClose={()=>setSelected(null)} footer={selected&&<>{(canDecide&&selected.status==='PENDING_MANAGER'||canHR&&selected.status==='PENDING_HR')&&<><button className="danger-outline" onClick={()=>{setSelected(null);setReject(selected)}}>رفض الطلب</button><button className="primary" onClick={()=>{void decide(selected.request_id,'APPROVE');setSelected(null)}}>اعتماد الطلب</button></>}</>}><div className="ux-detail-grid"><Detail label="الموظف" value={selected?.employee_name||selected?.employee_id}/><Detail label="نوع الإجازة" value={selected?.leave_type_name||typeName(selected?.leave_type_id)}/><Detail label="من" value={selected?.from_date}/><Detail label="إلى" value={selected?.to_date}/><Detail label="المدة" value={`${selected?.days??daysBetween(selected?.from_date,selected?.to_date)} يوم`}/><Detail label="الحالة"><Badge status={selected?.status}/></Detail><Detail label="السبب" value={selected?.reason||'—'} wide/></div><div className="ux-section"><h4>مسار الاعتماد</h4><div className="ux-timeline"><div className="ux-timeline-item"><i/><div><strong>تم إنشاء الطلب</strong><span>تم تسجيل الطلب في النظام</span></div></div><div className="ux-timeline-item"><i/><div><strong>اعتماد المدير</strong><span>{selected?.status==='PENDING_MANAGER'?'بانتظار القرار':'تم تجاوز هذه المرحلة'}</span></div></div><div className="ux-timeline-item"><i/><div><strong>الموارد البشرية</strong><span>{selected?.status==='PENDING_HR'?'بانتظار المراجعة':selected?.status==='APPROVED'?'تم الاعتماد':'حسب حالة الطلب'}</span></div></div></div></div></Drawer>
 <ConfirmDialog open={!!reject} title="رفض طلب الإجازة" description="اكتب سبب الرفض ليظهر في سجل الطلب ويكون واضحًا للموظف." confirmLabel="تأكيد الرفض" danger requireReason onClose={()=>setReject(null)} onConfirm={reason=>{if(reject)void decide(reject.request_id,'REJECT',reason)}}/>
 </section>
}
