'use client';
import { useEffect, useState } from 'react';
import { api } from '@/lib/api';
import { Badge, Empty } from './common';

const ratingText=(v:any)=>v?String(v):'لم يُقيّم بعد';
export default function Performance({employees,role}:{employees:any[];role:string}){
  const [reviews,setReviews]=useState<any[]>([]),[templates,setTemplates]=useState<any[]>([]),[goals,setGoals]=useState<any[]>([]),[plans,setPlans]=useState<any[]>([]),[busy,setBusy]=useState(true),[error,setError]=useState('');
  const [employeeId,setEmployeeId]=useState(''),[templateId,setTemplateId]=useState('');
  const [start,setStart]=useState(new Date().getFullYear()+'-01-01'),[end,setEnd]=useState(new Date().getFullYear()+'-12-31');
  const [scores,setScores]=useState<Record<string,number>>({});
  const [goalEmployee,setGoalEmployee]=useState(''),[goalTitle,setGoalTitle]=useState(''),[goalTarget,setGoalTarget]=useState(''),[goalDue,setGoalDue]=useState('');
  const [planEmployee,setPlanEmployee]=useState(''),[planTitle,setPlanTitle]=useState(''),[planObjective,setPlanObjective]=useState(''),[planDue,setPlanDue]=useState('');
  async function load(){try{setBusy(true);setError('');const [r,t,g,p]=await Promise.all([api<any[]>('performance_list'),api<any[]>('performance_templates'),api<any[]>('performance_goals'),api<any[]>('development_plans')]);setReviews(Array.isArray(r)?r:[]);setTemplates(Array.isArray(t)?t:[]);setGoals(Array.isArray(g)?g:[]);setPlans(Array.isArray(p)?p:[]);}catch(e:any){setError(e.message||'تعذر تحميل تقييمات الأداء')}finally{setBusy(false)}}
  useEffect(()=>{load()},[]);
  async function create(){try{setError('');if(!employeeId||!templateId)return setError('اختر الموظف ونموذج التقييم');await api('create_performance_review',{employee_id:employeeId,template_id:templateId,period_start:start,period_end:end});setEmployeeId('');await load()}catch(e:any){setError(e.message||'تعذر إنشاء التقييم')}}
  async function save(review:any){try{const items=(Array.isArray(templates.find(t=>t.template_id===review.template_id)?.performance_template_items)?templates.find(t=>t.template_id===review.template_id)?.performance_template_items:[]);const payload=items.map((i:any)=>({item_id:i.item_id,score:Number(scores[i.item_id]??0)}));await api('save_performance_scores',{review_id:review.review_id,scores:payload});await load()}catch(e:any){setError(e.message||'تعذر حفظ التقييم')}}
  async function decide(review:any,decision:string){try{await api('decide_performance_review',{review_id:review.review_id,decision});await load()}catch(e:any){setError(e.message||'تعذر تحديث التقييم')}}
  async function createGoal(){try{setError('');if(!goalEmployee||!goalTitle)return setError('اختر الموظف واكتب الهدف');await api('create_performance_goal',{employee_id:goalEmployee,title:goalTitle,target_value:goalTarget,due_date:goalDue||null,weight:0});setGoalTitle('');setGoalTarget('');setGoalDue('');await load()}catch(e:any){setError(e.message||'تعذر حفظ الهدف')}}
  async function createPlan(){try{setError('');if(!planEmployee||!planTitle||!planObjective)return setError('اختر الموظف واكتب عنوان الخطة والهدف التطويري');await api('create_development_plan',{employee_id:planEmployee,title:planTitle,objective:planObjective,due_date:planDue||null});setPlanTitle('');setPlanObjective('');setPlanDue('');await load()}catch(e:any){setError(e.message||'تعذر حفظ خطة التطوير')}}
  async function updateGoal(g:any,status:string,progress:number){try{await api('update_performance_goal',{goal_id:g.goal_id,status,progress_value:`${progress}%`});await load()}catch(e:any){setError(e.message||'تعذر تحديث الهدف')}}
  async function updatePlan(p:any,status:string,progress:number){try{await api('update_development_plan',{plan_id:p.plan_id,status,progress});await load()}catch(e:any){setError(e.message||'تعذر تحديث خطة التطوير')}}
  return <section className="panel page-panel performance-page"><div className="panel-head"><div><h2>تقييم الأداء والمهارات</h2><p>تقييم مرتبط بالوظيفة والقسم والمشروع والمدير، مع أوزان واضحة ومسار اعتماد.</p></div><span className="count-pill">{reviews.length} تقييم</span></div>
    {error&&<div className="state-card error-state">{error}</div>}
    <div className="request-card performance-create"><h3>إنشاء تقييم جديد</h3><div className="formgrid"><label><span>الموظف</span><select value={employeeId} onChange={e=>setEmployeeId(e.target.value)}><option value="">اختر الموظف</option>{employees.map(e=><option key={e.employee_id} value={e.employee_id}>{e.name} — {e.job_title||'بدون وظيفة'}</option>)}</select></label><label><span>نموذج التقييم</span><select value={templateId} onChange={e=>setTemplateId(e.target.value)}><option value="">اختر النموذج</option>{templates.map(t=><option key={t.template_id} value={t.template_id}>{t.name}</option>)}</select></label><label><span>من</span><input type="date" value={start} onChange={e=>setStart(e.target.value)}/></label><label><span>إلى</span><input type="date" value={end} onChange={e=>setEnd(e.target.value)}/></label><button className="primary" onClick={create}>إنشاء التقييم</button></div></div>
    <div className="performance-workspace">
      <div className="request-card performance-create"><h3>الأهداف الوظيفية</h3><p className="section-note">حدد هدفًا قابلًا للمتابعة واربطه بالموظف وتاريخ الإنجاز.</p><div className="formgrid"><label><span>الموظف</span><select value={goalEmployee} onChange={e=>setGoalEmployee(e.target.value)}><option value="">اختر الموظف</option>{employees.map(e=><option key={e.employee_id} value={e.employee_id}>{e.name} — {e.job_title||'بدون وظيفة'}</option>)}</select></label><label><span>الهدف</span><input value={goalTitle} onChange={e=>setGoalTitle(e.target.value)} placeholder="مثال: رفع دقة التقارير"/></label><label><span>مؤشر الإنجاز المستهدف</span><input value={goalTarget} onChange={e=>setGoalTarget(e.target.value)} placeholder="مثال: 95%"/></label><label><span>تاريخ الاستحقاق</span><input type="date" value={goalDue} onChange={e=>setGoalDue(e.target.value)}/></label><button className="primary" onClick={createGoal}>إضافة الهدف</button></div>
        {goals.length>0&&<div className="goal-list">{goals.map(g=><article className="goal-card" key={g.goal_id}><div><strong>{employees.find(e=>e.employee_id===g.employee_id)?.name||g.employee_id}</strong><h4>{g.title}</h4><span>{g.target_value||'مؤشر مستهدف غير محدد'} {g.due_date?`— الاستحقاق ${g.due_date}`:''}</span></div><div className="goal-actions"><Badge status={g.status}/>{g.status!=='ACHIEVED'&&g.status!=='CANCELLED'&&<><button className="secondary" onClick={()=>updateGoal(g,'ON_TRACK',50)}>تقدم 50%</button><button className="primary" onClick={()=>updateGoal(g,'ACHIEVED',100)}>تم الإنجاز</button></>}</div></article>)}</div>}
      </div>
      <div className="request-card performance-create"><h3>خطة التطوير الوظيفي</h3><p className="section-note">حوّل نقطة التحسين إلى خطوات واضحة ودعم وموعد متابعة.</p><div className="formgrid"><label><span>الموظف</span><select value={planEmployee} onChange={e=>setPlanEmployee(e.target.value)}><option value="">اختر الموظف</option>{employees.map(e=><option key={e.employee_id} value={e.employee_id}>{e.name} — {e.job_title||'بدون وظيفة'}</option>)}</select></label><label><span>عنوان الخطة</span><input value={planTitle} onChange={e=>setPlanTitle(e.target.value)} placeholder="مثال: تطوير مهارات القيادة"/></label><label><span>الهدف التطويري</span><input value={planObjective} onChange={e=>setPlanObjective(e.target.value)} placeholder="ما الذي يجب أن يتحسن؟"/></label><label><span>تاريخ المتابعة</span><input type="date" value={planDue} onChange={e=>setPlanDue(e.target.value)}/></label><button className="primary" onClick={createPlan}>إضافة خطة</button></div>
        {plans.length>0&&<div className="goal-list">{plans.map(p=><article className="goal-card" key={p.plan_id}><div><strong>{employees.find(e=>e.employee_id===p.employee_id)?.name||p.employee_id}</strong><h4>{p.title}</h4><span>{p.objective} {p.due_date?`— المتابعة ${p.due_date}`:''}</span></div><div className="goal-actions"><Badge status={p.status}/>{p.status!=='COMPLETED'&&p.status!=='CANCELLED'&&<><button className="secondary" onClick={()=>updatePlan(p,'IN_PROGRESS',50)}>قيد التنفيذ</button><button className="primary" onClick={()=>updatePlan(p,'COMPLETED',100)}>تم الإنجاز</button></>}</div></article>)}</div>}
      </div>
    </div>
    {busy?<div className="state-card">جاري تحميل التقييمات...</div>:!reviews.length?<Empty text="لا توجد تقييمات أداء حتى الآن."/>:<div className="performance-list">{reviews.map(r=><article className="performance-card" key={r.review_id}><div className="performance-head"><div><strong>{r.employees?.name||r.employee_id}</strong><span>{r.employees?.job_title||'—'} — {r.performance_templates?.name||'نموذج'}</span></div><Badge status={r.status}/></div><div className="performance-meta"><span>الفترة: {r.period_start} إلى {r.period_end}</span><strong>{r.overall_score?`${Number(r.overall_score).toFixed(2)} / 5`:'لم يُحسب'}</strong><b>{ratingText(r.final_rating)}</b></div>{r.status==='DRAFT'&&<div className="performance-score-box"><h4>درجات المعايير</h4>{(templates.find(t=>t.template_id===r.template_id)?.performance_template_items||[]).map((i:any)=><label key={i.item_id}><span>{i.title} — وزن {i.weight}%</span><input type="number" min="0" max={i.max_score} step="0.5" value={scores[i.item_id]??''} onChange={e=>setScores({...scores,[i.item_id]:Number(e.target.value)})}/></label>)}<button className="primary" onClick={()=>save(r)}>حفظ النتيجة</button></div>}{(r.status==='DRAFT'||r.status==='SUBMITTED')&&<div className="performance-actions"><button className="secondary" onClick={()=>decide(r,'MANAGER_APPROVE')}>اعتماد المدير</button><button className="danger" onClick={()=>decide(r,'CANCEL')}>إلغاء التقييم</button></div>}{r.status==='MANAGER_APPROVED'&&<div className="performance-actions"><button className="primary" onClick={()=>decide(r,'HR_CLOSE')}>إغلاق واعتماد الموارد البشرية</button></div>}</article>)}</div>}
  </section>
}
