'use client';
import { useMemo, useState } from 'react';
import { useEffect } from 'react';
import { api } from '@/lib/api';
import { Badge, employeeName } from './common';
import { ConfirmDialog, Detail, Drawer, Filters, Metric, PageHeader, TableShell } from './ui';
const types=[['GENERAL','إذن عام','إذن خلال ساعات العمل'],['PERSONAL','إذن شخصي','لشأن شخصي'],['MEDICAL','إذن طبي','لموعد أو متابعة طبية'],['EMERGENCY','إذن طارئ','حالة طارئة'],['OFFICIAL','إذن رسمي','مهمة رسمية'],['MISSION','مأمورية','عمل خارج الموقع'],['EARLY_DEPARTURE','انصراف مبكر','مغادرة قبل نهاية الوردية']];
const typeName=(v:string)=>types.find(x=>x[0]===v)?.[1]||v||'إذن';
function duration(a:string,b:string){if(!a||!b)return 0;const x=new Date(a),y=new Date(b);return y>x?Math.round((y.getTime()-x.getTime())/60000):0}
function durationLabel(min:number){const h=Math.floor(min/60),m=min%60;return h?`${h} ساعة${m?` و${m} دقيقة`:''}`:`${m} دقيقة`}
export default function PermissionSection({rows,employeeMode,permissionType,setPermissionType,permissionStart,setPermissionStart,permissionEnd,setPermissionEnd,permissionReason, setPermissionReason,createPermission,busy}:any){
 const safeRows=Array.isArray(rows)?rows:[];const [employees,setEmployees]=useState<any[]>([]);const [local,setLocal]=useState<any[]>(safeRows);const[q,setQ]=useState('');const[status,setStatus]=useState('ALL');const[selected,setSelected]=useState<any>(null);const[reject,setReject]=useState<any>(null);
 useEffect(()=>setLocal(Array.isArray(rows)?rows:[]),[rows]);
 useEffect(()=>{const needs=Array.isArray(rows)&&rows.some((r:any)=>!r?.employee_name&&r?.employee_id);if(!needs)return;void api<any[]>('employees').then(v=>setEmployees(Array.isArray(v)?v:[])).catch(()=>setEmployees([]));},[rows]);
 const filtered=useMemo(()=>local.filter(r=>(!q||`${r.employee_name||''} ${r.employee_id||''}`.toLowerCase().includes(q.toLowerCase()))&&(status==='ALL'||r.status===status)),[local,q,status]);
 const min=duration(permissionStart,permissionEnd); const displayStart=permissionStart?new Date(permissionStart).toLocaleString('ar-EG',{dateStyle:'medium',timeStyle:'short'}):'—'; const displayEnd=permissionEnd?new Date(permissionEnd).toLocaleString('ar-EG',{dateStyle:'medium',timeStyle:'short'}):'—';
 async function decide(id:string,decision:'APPROVE'|'REJECT',comment?:string){try{await api('decide_permission',{request_id:id,decision,comment});setLocal(p=>p.map(r=>r.request_id===id?{...r,status:decision==='APPROVE'?'APPROVED':'REJECTED'}:r));setReject(null)}catch(e:any){window.dispatchEvent(new CustomEvent('hr:toast',{detail:{message:e?.message||'تعذر تنفيذ القرار',type:'error'}}))}}
 return <section className="panel page-panel"><PageHeader title="الأذونات" subtitle="إدارة الأذونات دون إدخال أسماء أو أنواع داخلية، مع مدة ومسار اعتماد واضح." eyebrow="طلبات قصيرة المدة" count={<span className="count-pill">{filtered.length} طلب</span>}/>
 {employeeMode&&<div className="ux-card" style={{marginBottom:14}}><div className="request-card-headline"><div><h3>طلب إذن جديد</h3><p>حدد نوع الإذن ووقته ثم راجع المدة قبل الإرسال.</p></div></div><div className="permission-type-grid">{types.map(t=><button type="button" key={t[0]} className={`permission-type-option ${permissionType===t[0]?'active':''}`} onClick={()=>setPermissionType(t[0])}><strong>{t[1]}</strong><span>{t[2]}</span></button>)}</div><div className="ux-grid-2"><label className="ux-field"><span>بداية الإذن</span><input type="datetime-local" value={permissionStart} onChange={e=>setPermissionStart(e.target.value)}/></label><label className="ux-field"><span>نهاية الإذن</span><input type="datetime-local" value={permissionEnd} min={permissionStart||undefined} onChange={e=>setPermissionEnd(e.target.value)}/></label><label className="ux-field"><span>السبب</span><textarea value={permissionReason} onChange={e=>setPermissionReason(e.target.value)} rows={3} placeholder="اكتب سبب الإذن"/></label></div><div className="permission-duration-preview"><span>مدة الإذن</span><strong>{min?durationLabel(min):'حدد وقت البداية والنهاية'}</strong></div><button className="primary" disabled={busy||!permissionStart||!permissionEnd||!permissionReason||min<1} onClick={createPermission}>{busy?'جاري الإرسال...':'إرسال الطلب'}</button></div>}
 <Filters onReset={()=>{setQ('');setStatus('ALL')}}><label className="ux-field"><span>بحث</span><input value={q} onChange={e=>setQ(e.target.value)} placeholder="اسم الموظف أو الرقم الوظيفي"/></label><label className="ux-field"><span>الحالة</span><select value={status} onChange={e=>setStatus(e.target.value)}><option value="ALL">كل الحالات</option><option value="PENDING">بانتظار الاعتماد</option><option value="APPROVED">معتمد</option><option value="REJECTED">مرفوض</option></select></label></Filters>
 <TableShell title="طلبات الأذونات" count={`${filtered.length} نتيجة`} empty={!filtered.length?'لا توجد طلبات إذن مطابقة.':undefined}><table><thead><tr><th>الموظف</th><th>النوع</th><th>التاريخ</th><th>الوقت</th><th>المدة</th><th>الحالة</th><th>إجراء</th></tr></thead><tbody>{filtered.map(r=><tr key={r.request_id} onClick={()=>setSelected(r)}><td><div className="ux-person"><span className="ux-avatar">{employeeName(r, employees).charAt(0)}</span><span><strong>{employeeName(r, employees)}</strong><small>{r.employee_id||'—'}</small></span></div></td><td>{typeName(r.permission_type||r.type)}</td><td>{r.start_time?new Date(r.start_time).toLocaleDateString('ar-EG'):'—'}</td><td>{r.start_time&&r.end_time?`${new Date(r.start_time).toLocaleTimeString('ar-EG',{hour:'2-digit',minute:'2-digit'})} — ${new Date(r.end_time).toLocaleTimeString('ar-EG',{hour:'2-digit',minute:'2-digit'})}`:'—'}</td><td>{r.minutes?durationLabel(Number(r.minutes)):durationLabel(duration(r.start_time,r.end_time))}</td><td><Badge status={r.status}/></td><td>{r.status==='PENDING'&&<div className="ux-action-row"><button className="secondary" onClick={e=>{e.stopPropagation();void decide(r.request_id,'APPROVE')}}>اعتماد</button><button className="danger-outline" onClick={e=>{e.stopPropagation();setReject(r)}}>رفض</button></div>}</td></tr>)}</tbody></table></TableShell>
 <Drawer open={!!selected} title="تفاصيل طلب الإذن" subtitle={selected?.request_id} onClose={()=>setSelected(null)} footer={selected?.status==='PENDING'&&<><button className="danger-outline" onClick={()=>{setReject(selected);setSelected(null)}}>رفض الطلب</button><button className="primary" onClick={()=>{void decide(selected.request_id,'APPROVE');setSelected(null)}}>اعتماد الطلب</button></>}><div className="ux-detail-grid"><Detail label="الموظف" value={employeeName(selected,employees)}/><Detail label="نوع الإذن" value={typeName(selected?.permission_type||selected?.type)}/><Detail label="التاريخ" value={selected?.start_time?new Date(selected.start_time).toLocaleDateString('ar-EG'):'—'}/><Detail label="البداية" value={selected?.start_time?new Date(selected.start_time).toLocaleTimeString('ar-EG',{hour:'2-digit',minute:'2-digit'}):'—'}/><Detail label="النهاية" value={selected?.end_time?new Date(selected.end_time).toLocaleTimeString('ar-EG',{hour:'2-digit',minute:'2-digit'}):'—'}/><Detail label="المدة" value={selected?.minutes?durationLabel(Number(selected.minutes)):durationLabel(duration(selected?.start_time,selected?.end_time))}/><Detail label="الحالة"><Badge status={selected?.status}/></Detail><Detail label="السبب" value={selected?.reason||'—'} wide/></div><div className="ux-section"><h4>مسار الطلب</h4><div className="ux-timeline"><div className="ux-timeline-item"><i/><div><strong>تم إنشاء الطلب</strong><span>{displayStart}</span></div></div><div className="ux-timeline-item"><i/><div><strong>المراجعة</strong><span>{selected?.status==='PENDING'?'بانتظار قرار المسؤول':'تم إصدار القرار'}</span></div></div><div className="ux-timeline-item"><i/><div><strong>النتيجة</strong><span>{selected?.status==='APPROVED'?'تم الاعتماد':selected?.status==='REJECTED'?'تم الرفض':'لم يصدر القرار بعد'}</span></div></div></div></div></Drawer>
 <ConfirmDialog open={!!reject} title="رفض طلب الإذن" description="سبب الرفض إلزامي حتى يعرف الموظف سبب القرار." confirmLabel="تأكيد الرفض" danger requireReason onClose={()=>setReject(null)} onConfirm={reason=>{if(reject)void decide(reject.request_id,'REJECT',reason)}}/>
 </section>
}
