import Icon from './Icon';
import { useState } from 'react';

type Tab='overview'|'attendance'|'roles'|'operations';
const roleCards=[
 {role:'SYSTEM_ADMIN',title:'مدير النظام',tone:'blue',text:'تحكم كامل في النظام: الموظفون، المشاريع، الورديات، الحسابات، التعيينات، الطلبات والإعدادات.'},
 {role:'HR_MANAGER',title:'مدير الموارد البشرية',tone:'green',text:'إدارة الموظفين وطلبات الإجازات والأذونات والخصومات ومتابعة القوى العاملة وفق نطاق HR.'},
 {role:'SECTOR_MANAGER',title:'مدير القطاع',tone:'amber',text:'إدارة المشروعات المسندة إليه ومتابعة مديري المشاريع والطلبات. لا يوجد له حضور أو انصراف.'},
 {role:'PROJECT_MANAGER',title:'مدير المشروع',tone:'navy',text:'موظف داخل الشركة وله حضور وانصراف، ويدير الموظفين والطلبات داخل مشروعاته فقط.'},
 {role:'EMPLOYEE',title:'الموظف',tone:'slate',text:'حضور وانصراف وطلبات الإجازات والأذونات الخاصة به.'},
];
export default function Settings(){
 const [tab,setTab]=useState<Tab>('overview');
 const tabs:[Tab,string,string][]=[['overview','نظرة عامة','dashboard'],['attendance','الحضور والورديات','attendance'],['roles','الأدوار والصلاحيات','users'],['operations','قواعد التشغيل','settings']];
 return <section className="panel page-panel hr-settings"><div className="hr-settings-hero"><div><div className="eyebrow">ELNUBY HR • CONTROL CENTER</div><h2>إعدادات النظام</h2><p>مركز موحد لفهم تشغيل النظام والصلاحيات وقواعد الحضور بدون تعقيد.</p></div><div className="hr-system-status"><span className="status-dot"/> النظام متصل</div></div>
  <div className="hr-settings-tabs">{tabs.map(([id,label,icon])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}><span>{icon}</span><b>{label}</b></button>)}</div>
  {tab==='overview'&&<div className="hr-settings-body"><div className="hr-stat-grid"><div><span>الحضور</span><strong>مفعل</strong><small>حسب الوردية والموقع</small></div><div><span>الجلسات</span><strong>محمي</strong><small>جلسات موقعة ومدة محددة</small></div><div><span>الاعتماد</span><strong>متدرج</strong><small>مدير مشروع ← HR</small></div><div><span>التدقيق</span><strong>Audit</strong><small>للعمليات الإدارية الحساسة</small></div></div><div className="hr-settings-columns"><section><div className="hr-section-title"><span>01</span><div><h3>كيف يعمل النظام؟</h3><p>تسلسل العمل من الموظف إلى الإدارة.</p></div></div>{[['ربط الموظف','المشروع والوردية الحالية يحددان نطاق الحضور.'],['الحضور','يتم التحقق من الوقت والـGPS ونطاق المشروع.'],['الطلبات','الإجازات والأذونات تمر بمسار اعتماد واضح.'],['الإدارة','مدير النظام يدير البيانات من داخل البرنامج.']].map(([a,b])=><div className="hr-rule" key={a}><b>{a}</b><span>{b}</span></div>)}</section><aside><div className="hr-section-title"><span>02</span><div><h3>مصادر الإعداد</h3><p>المصدر الحقيقي لكل قاعدة.</p></div></div>{[['الورديات','شاشة الورديات'],['المشروعات','شاشة المشاريع'],['الحسابات','حسابات المستخدمين'],['الصلاحيات','Backend + Role Scope']].map(([a,b])=><div className="hr-source" key={a}><span>{a}</span><b>{b}</b></div>)}</aside></div></div>}
  {tab==='attendance'&&<div className="hr-settings-body"><div className="hr-feature"><div className="feature-icon blue"><Icon name="attendance" /></div><div><h3>محرك الحضور والانصراف</h3><p>الحضور والانصراف لا يعتمدان على زر الواجهة فقط؛ الـBackend يتحقق من الدور والوردية والوقت وموقع المشروع.</p></div></div><div className="hr-rule-grid">{[['فتح الحضور','من attendance_open إلى attendance_close'],['التأخير','بعد start_time يحسب late_minutes'],['فتح الانصراف','لا يسمح قبل checkout_open'],['الإغلاق التلقائي','auto_checkout_time يغلق السجل المفتوح'],['الموقع','GPS + geofence_radius_m'],['التاريخ','توقيت التشغيل Africa/Cairo (APP_TIMEZONE)']].map(([a,b])=><div className="hr-rule-card" key={a}><b>{a}</b><span>{b}</span></div>)}</div></div>}
  {tab==='roles'&&<div className="hr-settings-body"><div className="hr-role-grid">{roleCards.map(c=><article className={`hr-role-card ${c.tone}`} key={c.role}><div className="role-code">{c.role}</div><h3>{c.title}</h3><p>{c.text}</p></article>)}</div></div>}
  {tab==='operations'&&<div className="hr-settings-body"><div className="hr-operation-grid">{[['التعيينات','الموظف يمكن أن يكون له تعيين حالي واحد للمشروع، مع الاحتفاظ بالتاريخ.'],['الورديات','لا نحذف وردية مرتبطة بسجلات تاريخية؛ يتم تعطيلها بدل كسر العلاقات.'],['مدير القطاع','له نطاق مشروعات مستقل ولا يُعامل كمشرف موقع.'],['مدير المشروع','حساب إداري + موظف فعلي في نفس الوقت.'],['مدير النظام','CRUD كامل من داخل البرنامج مع مرور العمليات عبر Backend وAudit.'],['الخصوصية','النطاق يطبق في Backend وليس بإخفاء عناصر الواجهة فقط.']].map(([a,b])=><article key={a}><div className="operation-icon"><Icon name="check" size={15}/></div><div><h3>{a}</h3><p>{b}</p></div></article>)}</div></div>}
 </section>;
}
