'use client';
import { useMemo, useState } from 'react';
import type { Shift, Row } from './types';
import { Badge } from './common';
import { Detail, Drawer, Filters, Metric, PageHeader, TableShell } from './ui';
function time12(v?:string){if(!v)return '—';const [h,m]=String(v).slice(0,5).split(':').map(Number);if(!Number.isFinite(h))return v;return `${(h%12)||12}:${String(m||0).padStart(2,'0')} ${h>=12?'م':'ص'}`}
export default function Shifts({shifts,rows,managerMode,shiftForm,setShiftForm,createShift,busy,onEdit}:{shifts:Shift[];rows:Row[];managerMode:boolean;shiftForm:any;setShiftForm:any;createShift:()=>void;busy:boolean;onEdit?:(shiftId:string)=>void}){
 const safeShifts=Array.isArray(shifts)?shifts:[]; const safeRows=Array.isArray(rows)?rows:[]; const [q,setQ]=useState('');const[selected,setSelected]=useState<Shift|null>(null);
 const filtered=useMemo(()=>safeShifts.filter(s=>!q||String(s.name).toLowerCase().includes(q.toLowerCase())),[safeShifts,q]);
 return <section className="panel page-panel"><PageHeader title="الورديات" subtitle="ضبط ساعات العمل ونوافذ الحضور والانصراف والإغلاق التلقائي." eyebrow="إدارة الوقت" count={<span className="count-pill">{safeShifts.length} وردية</span>} actions={!managerMode?<button className="primary" onClick={createShift} disabled={busy||!shiftForm.name}>إنشاء الوردية</button>:null}/>
 <div className="ux-metric-grid"><Metric label="الورديات النشطة" value={safeShifts.filter(s=>s.status==='ACTIVE'||!s.status).length} caption="جاهزة للتعيين" tone="green" icon="check"/><Metric label="تعيينات اليوم" value={safeRows.filter(r=>!r.end_date).length} caption="التعيينات الحالية" icon="users"/><Metric label="نافذة الحضور" value="09:30 ص" caption="حسب الإعداد الافتراضي" tone="amber" icon="attendance"/><Metric label="الإغلاق التلقائي" value="مفعل" caption="حسب الوردية" tone="purple" icon="attendance"/></div>
 {!managerMode&&<div className="ux-card" style={{marginBottom:14}}><div className="request-card-headline"><div><h3>إضافة وردية</h3><p>أنشئ وردية كاملة مرة واحدة ثم استخدم التعديل المتخصص عند الحاجة.</p></div></div><div className="ux-grid-2"><label className="ux-field"><span>اسم الوردية *</span><input value={shiftForm.name} onChange={e=>setShiftForm({...shiftForm,name:e.target.value})}/></label><label className="ux-field"><span>بداية العمل</span><input type="time" value={shiftForm.start_time} onChange={e=>setShiftForm({...shiftForm,start_time:e.target.value})}/></label><label className="ux-field"><span>فتح الحضور</span><input type="time" value={shiftForm.attendance_open} onChange={e=>setShiftForm({...shiftForm,attendance_open:e.target.value})}/></label><label className="ux-field"><span>إغلاق الحضور</span><input type="time" value={shiftForm.attendance_close} onChange={e=>setShiftForm({...shiftForm,attendance_close:e.target.value})}/></label><label className="ux-field"><span>فتح الانصراف</span><input type="time" value={shiftForm.checkout_open} onChange={e=>setShiftForm({...shiftForm,checkout_open:e.target.value})}/></label><label className="ux-field"><span>إغلاق الانصراف</span><input type="time" value={shiftForm.checkout_close} onChange={e=>setShiftForm({...shiftForm,checkout_close:e.target.value})}/></label><label className="ux-field"><span>الإغلاق التلقائي</span><input type="time" value={shiftForm.auto_checkout_time} onChange={e=>setShiftForm({...shiftForm,auto_checkout_time:e.target.value})}/></label></div></div>}
 <Filters onReset={()=>setQ('')}><label className="ux-field"><span>بحث عن وردية</span><input value={q} onChange={e=>setQ(e.target.value)} placeholder="اسم الوردية"/></label></Filters>
 <TableShell title="الورديات" count={`${filtered.length} نتيجة`} empty={!filtered.length?'لا توجد ورديات.':undefined}><table><thead><tr><th>الوردية</th><th>بداية العمل</th><th>الحضور</th><th>الانصراف</th><th>الإغلاق التلقائي</th><th>الحالة</th><th>إجراء</th></tr></thead><tbody>{filtered.map(s=><tr key={s.shift_id} onClick={()=>setSelected(s)}><td><strong>{s.name}</strong><small>{s.shift_id}</small></td><td>{time12(s.start_time)}</td><td>{time12(s.attendance_open)} — {time12(s.attendance_close)}</td><td>{time12(s.checkout_open)} — {time12(s.checkout_close)}</td><td>{time12(s.auto_checkout_time)}</td><td><Badge status={s.status||'ACTIVE'}/></td><td>{onEdit&&<button className="table-action" onClick={e=>{e.stopPropagation();onEdit(s.shift_id)}} disabled={busy}>تعديل</button>}</td></tr>)}</tbody></table></TableShell>
 <TableShell title="التعيينات الحالية»"><table><thead><tr><th>الموظف</th><th>المشروع</th><th>الوردية</th><th>من تاريخ</th><th>إلى تاريخ</th><th>الحالة</th></tr></thead><tbody>{safeRows.map((r:any,i:number)=><tr key={r.assignment_id||i}><td>{r.employee_name||r.employee_id}</td><td>{r.project_name||r.project_id}</td><td>{r.shift_name||r.shift_id}</td><td>{r.start_date||'—'}</td><td>{r.end_date||'—'}</td><td><Badge status={r.end_date?'HISTORY':'CURRENT'}/></td></tr>)}</tbody></table></TableShell>
 <Drawer open={!!selected} title={selected?.name||'الوردية'} subtitle={selected?.shift_id} onClose={()=>setSelected(null)}><div className="ux-detail-grid"><Detail label="بداية العمل" value={time12(selected?.start_time)}/><Detail label="الحالة"><Badge status={selected?.status||'ACTIVE'}/></Detail><Detail label="فتح الحضور" value={time12(selected?.attendance_open)}/><Detail label="إغلاق الحضور" value={time12(selected?.attendance_close)}/><Detail label="فتح الانصراف" value={time12(selected?.checkout_open)}/><Detail label="إغلاق الانصراف" value={time12(selected?.checkout_close)}/><Detail label="الإغلاق التلقائي" value={time12(selected?.auto_checkout_time)} wide/></div></Drawer>
 </section>
}
