'use client';
import { useMemo, useState } from 'react';
import type { User, Employee, Project } from './types';
import { roleLabels } from './constants';
import { Badge } from './common';
import { Detail, Drawer, Filters, Metric, PageHeader, TableShell } from './ui';
const roles=[['EMPLOYEE','موظف'],['PROJECT_MANAGER','مدير مشروع'],['SECTOR_MANAGER','مدير قطاع'],['HR_MANAGER','مدير الموارد البشرية'],['SYSTEM_ADMIN','مدير النظام']];
export default function Users({users,employees,projects,newUsername,setNewUsername,newPassword,setNewPassword,newRole,setNewRole,newEmployee,setNewEmployee,newProject,setNewProject,selectedSectorProjects,setSelectedSectorProjects,selectedSectorManager,setSelectedSectorManager,selectedManager,setSelectedManager,selectedProject,setSelectedProject,assignManager,assignSectorManagerProjects,createAccount,busy,onRefresh,onToggleUser,onResetPassword}:any){
 const us=Array.isArray(users)?users:[], es=Array.isArray(employees)?employees:[], ps=Array.isArray(projects)?projects:[]; const [q,setQ]=useState('');const [role,setRole]=useState('ALL');const [selected,setSelected]=useState<User|null>(null);
 const filtered=useMemo(()=>us.filter(u=>(!q||`${u.username} ${u.employee_id||''}`.toLowerCase().includes(q.toLowerCase()))&&(role==='ALL'||u.role===role)),[us,q,role]);
 return <section className="panel page-panel"><PageHeader title="حسابات المستخدمين" subtitle="إدارة الحسابات والأدوار والارتباطات التشغيلية من شاشة واحدة." eyebrow="إدارة الوصول" count={<span className="count-pill">{us.length} حساب</span>} actions={<button className="secondary" onClick={onRefresh} disabled={busy}>تحديث</button>}/>
 <div className="ux-metric-grid"><Metric label="إجمالي الحسابات" value={us.length} icon="users"/><Metric label="الحسابات النشطة" value={us.filter(u=>u.status==='ACTIVE').length} tone="green" icon="check"/><Metric label="مديرو المشاريع" value={us.filter(u=>u.role==='PROJECT_MANAGER').length} tone="amber" icon="projects"/><Metric label="مديرو الموارد البشرية" value={us.filter(u=>u.role==='HR_MANAGER').length} tone="purple" icon="settings"/></div>
 <div className="ux-card" style={{marginBottom:14}}><div className="request-card-headline"><div><h3>إنشاء حساب</h3><p>أكمل البيانات الأساسية فقط؛ الارتباطات الإدارية تظهر حسب الدور المختار.</p></div></div><div className="ux-grid-2"><label className="ux-field"><span>اسم المستخدم *</span><input value={newUsername} onChange={e=>setNewUsername(e.target.value)}/></label><label className="ux-field"><span>كلمة المرور *</span><input type="password" value={newPassword} onChange={e=>setNewPassword(e.target.value)}/></label><label className="ux-field"><span>الدور *</span><select value={newRole} onChange={e=>setNewRole(e.target.value)}>{roles.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>{['EMPLOYEE','PROJECT_MANAGER','SECTOR_MANAGER'].includes(newRole)&&<label className="ux-field"><span>الموظف المرتبط *</span><select value={newEmployee} onChange={e=>setNewEmployee(e.target.value)}><option value="">اختر الموظف</option>{es.map(e=><option key={e.employee_id} value={e.employee_id}>{e.name}</option>)}</select></label>}{newRole==='PROJECT_MANAGER'&&<label className="ux-field"><span>المشروع</span><select value={newProject} onChange={e=>setNewProject(e.target.value)}><option value="">اختر المشروع</option>{ps.map(p=><option key={p.project_id} value={p.project_id}>{p.name}</option>)}</select></label>}{newRole==='SECTOR_MANAGER'&&<label className="ux-field"><span>مشروعات مدير القطاع</span><select multiple value={selectedSectorProjects||[]} onChange={e=>setSelectedSectorProjects(Array.from(e.target.selectedOptions).map(o=>o.value))}>{ps.map(p=><option key={p.project_id} value={p.project_id}>{p.name}</option>)}</select></label>}</div><button className="primary" onClick={createAccount} disabled={busy||!newUsername||!newPassword}>إنشاء الحساب</button></div>
 <div className="ux-grid-2"><div className="ux-card"><h3>ربط مدير مشروع</h3><p>اختر المدير والمشروع لحفظ نطاق الإدارة.</p><div className="ux-grid-2"><label className="ux-field"><span>المدير</span><select value={selectedManager} onChange={e=>setSelectedManager(e.target.value)}><option value="">اختر</option>{us.filter(u=>u.role==='PROJECT_MANAGER'&&u.status==='ACTIVE').map(u=><option key={u.user_id} value={u.user_id}>{u.username}</option>)}</select></label><label className="ux-field"><span>المشروع</span><select value={selectedProject} onChange={e=>setSelectedProject(e.target.value)}><option value="">اختر</option>{ps.map(p=><option key={p.project_id} value={p.project_id}>{p.name}</option>)}</select></label></div><button className="secondary" disabled={!selectedManager||!selectedProject||busy} onClick={assignManager}>حفظ الربط</button></div><div className="ux-card"><h3>مشروعات مدير القطاع</h3><p>حدد نطاق المشروعات المتاح لهذا الدور.</p><label className="ux-field"><span>مدير القطاع</span><select value={selectedSectorManager} onChange={e=>setSelectedSectorManager(e.target.value)}><option value="">اختر</option>{us.filter(u=>u.role==='SECTOR_MANAGER'&&u.status==='ACTIVE').map(u=><option key={u.user_id} value={u.user_id}>{u.username}</option>)}</select></label><button className="secondary" disabled={!selectedSectorManager||!(selectedSectorProjects||[]).length||busy} onClick={assignSectorManagerProjects}>حفظ النطاق</button></div></div>
 <Filters onReset={()=>{setQ('');setRole('ALL')}}><label className="ux-field"><span>بحث</span><input value={q} onChange={e=>setQ(e.target.value)} placeholder="اسم المستخدم أو الرقم الوظيفي"/></label><label className="ux-field"><span>الدور</span><select value={role} onChange={e=>setRole(e.target.value)}><option value="ALL">كل الأدوار</option>{roles.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label></Filters>
 <TableShell title="الحسابات" count={`${filtered.length} نتيجة`} empty={!filtered.length?'لا توجد حسابات مطابقة.':undefined}><table><thead><tr><th>الحساب</th><th>الدور</th><th>الموظف</th><th>الحالة</th><th>آخر دخول</th><th>إجراءات</th></tr></thead><tbody>{filtered.map(u=><tr key={u.user_id} onClick={()=>setSelected(u)}><td><div className="ux-person"><span className="ux-avatar">{String(u.username||'?').charAt(0)}</span><span><strong>{u.username}</strong><small>{u.user_id}</small></span></div></td><td>{roleLabels[u.role]||u.role}</td><td>{u.employee_id||'—'}</td><td><Badge status={u.status}/></td><td>{u.last_login?new Date(u.last_login).toLocaleString('ar-EG'):'—'}</td><td><div className="ux-action-row"><button className="secondary" onClick={e=>{e.stopPropagation();onToggleUser?.(u.user_id,u.status)}} disabled={busy}>{u.status==='ACTIVE'?'تعطيل':'تفعيل'}</button><button className="secondary" onClick={e=>{e.stopPropagation();onResetPassword?.(u.user_id)}} disabled={busy}>تغيير كلمة المرور</button></div></td></tr>)}</tbody></table></TableShell>
 <Drawer open={!!selected} title={selected?.username||'الحساب'} subtitle={selected?.user_id} onClose={()=>setSelected(null)}><div className="ux-detail-grid"><Detail label="الدور" value={(selected?.role ? roleLabels[selected.role] : undefined)||selected?.role}/><Detail label="الحالة"><Badge status={selected?.status}/></Detail><Detail label="الموظف" value={selected?.employee_id}/><Detail label="آخر دخول" value={selected?.last_login?new Date(selected.last_login).toLocaleString('ar-EG'):'—'}/></div></Drawer>
 </section>
}
