const fs = require('fs');
const assert = require('assert');
const leave = fs.readFileSync('src/components/hr/LeaveSection.tsx','utf8');
const perm = fs.readFileSync('src/components/hr/PermissionSection.tsx','utf8');
const leavesServer = fs.readFileSync('src/server/hr/leaves.ts','utf8');
const permsServer = fs.readFileSync('src/server/hr/permissions.ts','utf8');
const router = fs.readFileSync('src/server/hr/router.ts','utf8');
const migration = fs.readFileSync('supabase/migrations/20260830_leave_permission_workflow_upgrade.sql','utf8');
assert.ok(leave.includes('leave_balances'));
assert.ok(leave.includes('statusFilter'));
assert.ok(leave.includes('cancel_leave'));
assert.ok(leave.includes('REQUEST DETAILS'));
assert.ok(perm.includes('PERMISSION_TYPES'));
assert.ok(perm.includes('cancel_permission'));
assert.ok(permsServer.includes('status:"CANCELLED"'));
assert.ok(leavesServer.includes('status:"CANCELLED"'));
assert.ok(leavesServer.includes('decision === "REJECT" && comment.length < 3'));
assert.ok(permsServer.includes('سبب الرفض مطلوب'));
assert.ok(router.includes('case "cancel_leave"'));
assert.ok(router.includes('case "cancel_permission"'));
assert.ok(migration.includes('cancelled_at'));
assert.ok(migration.includes("'CANCELLED'"));
console.log('PASS leave/permission workflow upgrade regression');
