'use client';
import {useEffect,useState} from 'react';
import {api} from '@/lib/api';

type Employee={employee_id:string;name:string;job_title?:string};
type User={user_id:string;employee_id:string;username:string;role:string;status:string;last_login?:string;created_at?:string};

export default function Home(){
 const [username,setUsername]=useState(''); const [password,setPassword]=useState(''); const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const [me,setMe]=useState<any>(null); const [dash,setDash]=useState<any>(null);
 const [users,setUsers]=useState<User[]>([]); const [employees,setEmployees]=useState<Employee[]>([]);
 const [newUsername,setNewUsername]=useState(''); const [newPassword,setNewPassword]=useState(''); const [newRole,setNewRole]=useState('EMPLOYEE'); const [newEmployee,setNewEmployee]=useState(''); const [userMsg,setUserMsg]=useState('');
 useEffect(()=>{if(localStorage.getItem('hr_token')) load();},[]);
 async function load(){try{const m:any=await api('me');setMe(m);setDash(await api('dashboard')); if(m.user?.role==='SUPER_ADMIN'){setUsers(await api('users'));setEmployees(await api('employees'));}}catch{localStorage.removeItem('hr_token');}}
 async function login(){setBusy(true);setError('');try{const r:any=await api('login',{username,password});localStorage.setItem('hr_token',r.token);await load();}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function locate(action:string){setError('');if(!navigator.geolocation)return setError('المتصفح لا يدعم GPS');setBusy(true);navigator.geolocation.getCurrentPosition(async p=>{try{await api(action,{latitude:p.coords.latitude,longitude:p.coords.longitude});await load()}catch(e:any){setError(e.message)}finally{setBusy(false)}},()=>{setError('يجب السماح بالموقع لتسجيل الحضور/الانصراف');setBusy(false)},{enableHighAccuracy:true,timeout:10000});}
 async function createAccount(){setUserMsg('');setError('');if(newRole==='EMPLOYEE'&&!newEmployee)return setUserMsg('اختر الموظف المرتبط بالحساب');setBusy(true);try{await api('create_user',{username:newUsername,password:newPassword,role:newRole,employee_id:newEmployee,status:'ACTIVE'});setUserMsg('تم إنشاء الحساب بنجاح');setNewUsername('');setNewPassword('');setNewEmployee('');setNewRole('EMPLOYEE');setUsers(await api('users'));}catch(e:any){setUserMsg(e.message)}finally{setBusy(false)}}
 if(!me)return <main className="center"><section className="card login"><h1>Site HR</h1><p>إدارة موظفي ومشاريع شركة المقاولات</p><input placeholder="اسم المستخدم" value={username} onChange={e=>setUsername(e.target.value)}/><input type="password" placeholder="كلمة المرور" value={password} onChange={e=>setPassword(e.target.value)}/><button disabled={busy} onClick={login}>{busy?'جاري الدخول…':'تسجيل الدخول'}</button>{error&&<div className="error">{error}</div>}</section></main>;
 return <main className="page"><header><div><h1>مرحباً {me.employee?.name||me.user?.username||''}</h1><span>{me.user?.role}</span></div><button className="ghost" onClick={()=>{localStorage.removeItem('hr_token');location.reload()}}>خروج</button></header><section className="grid">{[['الموظفون',dash?.employees],['حضور اليوم',dash?.present],['متأخرون',dash?.late],['بدون انصراف',dash?.missingCheckout]].map(([t,v])=><div className="stat card" key={t as string}><small>{t}</small><strong>{v??'-'}</strong></div>)}</section><section className="card attendance"><h2>الحضور والانصراف</h2><div className="actions"><button disabled={busy} onClick={()=>locate('check_in')}>تسجيل الحضور</button><button disabled={busy} onClick={()=>locate('check_out')}>تسجيل الانصراف</button><button className="secondary">طلب إذن</button><button className="secondary">طلب إجازة</button></div>{error&&<div className="error">{error}</div>}</section>{me.user?.role==='SUPER_ADMIN'&&<section className="card admin"><h2>إدارة حسابات المستخدمين</h2><p>أنشئ حسابات الموظفين والمديرين من داخل النظام. كلمة المرور لا تُخزّن كنص صريح.</p><div className="formgrid"><input placeholder="اسم المستخدم" value={newUsername} onChange={e=>setNewUsername(e.target.value)}/><input type="password" placeholder="كلمة المرور" value={newPassword} onChange={e=>setNewPassword(e.target.value)}/><select value={newRole} onChange={e=>setNewRole(e.target.value)}><option value="EMPLOYEE">موظف</option><option value="PROJECT_MANAGER">مدير مشروع</option><option value="HR_MANAGER">HR Manager</option><option value="SUPER_ADMIN">Super Admin</option></select>{newRole==='EMPLOYEE'?<select value={newEmployee} onChange={e=>setNewEmployee(e.target.value)}><option value="">اختر الموظف</option>{employees.map(e=><option key={e.employee_id} value={e.employee_id}>{e.name} — {e.employee_id}</option>)}</select>:<div/>}</div><button disabled={busy} onClick={createAccount}>إنشاء الحساب</button>{userMsg&&<div className={userMsg.includes('نجاح')?'success':'error'}>{userMsg}</div>}<div className="tablewrap"><table><thead><tr><th>Username</th><th>Role</th><th>Employee</th><th>Status</th><th>Last Login</th></tr></thead><tbody>{users.map(u=><tr key={u.user_id}><td>{u.username}</td><td>{u.role}</td><td>{u.employee_id||'—'}</td><td>{u.status}</td><td>{u.last_login||'—'}</td></tr>)}</tbody></table></div></section>}</main>
}
